apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: jackett
  namespace: media
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: jackett
  updatePolicy:
    updateMode: "Auto"
    minReplicas: 1
