apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: sonarr
  namespace: media
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: sonarr
  updatePolicy:
    updateMode: "Recreate"
    minReplicas: 1
