apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: transmission-openvpn
  namespace: media
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: transmission-openvpn
  updatePolicy:
    updateMode: "Recreate"
    minReplicas: 1
