apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: unifi-controller
  namespace: unifi
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: StatefulSet
    name: unifi-controller
  updatePolicy:
    updateMode: "Recreate"
    minReplicas: 1
