apiVersion: apps/v1
kind: Deployment
metadata:
  name: changedetection
  namespace: changedetection
  labels:
    app: changedetection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: changedetection
  template:
    metadata:
      labels:
        app: changedetection
    spec:
      containers:
        - name: changedetection
          image: dgtlmoon/changedetection.io:0.39.6
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: changedetection-volume
              mountPath: /datastore
              subPath: changedetection/
          ports:
            - containerPort: 5000
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi
      nodeSelector:
        beta.kubernetes.io/arch: arm
        beta.kubernetes.io/os: linux
      volumes:
        - name: changedetection-volume
          persistentVolumeClaim:
            claimName: changedetection-ssd
