apiVersion: v1
kind: Service
metadata:
  namespace: changedetection
  labels:
    app: changedetection
  name: changedetection
spec:
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
  selector:
    app: changedetection
  externalIPs:
    - "192.168.3.240"
