apiVersion: apps/v1
kind: Deployment
metadata:
  name: changedetection
  namespace: changedetection
  labels:
    app: changedetection
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: changedetection
  template:
    metadata:
      labels:
        app: changedetection
    spec:
      containers:
        - env:
            - name: WEBDRIVER_URL
              value: http://selenium:4444/wd/hub
          name: changedetection
          image: dgtlmoon/changedetection.io:0.45.1
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: changedetection
              mountPath: /datastore
          ports:
            - containerPort: 5000
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi
      volumes:
        - name: changedetection
          persistentVolumeClaim:
            claimName: changedetection
