apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: changedetection
  namespace: changedetection
  labels:
    app: changedetection
spec:
  storageClassName: nfs-rpik3s
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
