apiVersion: v1
kind: PersistentVolume
metadata:
  name: changedetection-ssd
  namespace: changedetection
  labels:
    app: changedetection
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/ssd/changedetection
