apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: changedetection-ssd
  namespace: changedetection
  labels:
    app: changedetection
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
