apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium
  namespace: changedetection
  labels:
    app: selenium
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: selenium
  template:
    metadata:
      annotations:
        pod.beta.kubernetes.io/hostname: selenium
      labels:
        app: selenium
    spec:
      containers:
        - env:
          - name: FETCH_WORKERS
            value: "2"
          name: selenium
          image: seleniarm/standalone-chromium:4.0.0-20211213
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /dev/shm
              name: dshm
          ports:
            - containerPort: 4444
              protocol: TCP
          resources:
            limits:
              memory: 256Mi
            requests:
              cpu: 500m
              memory: 256Mi
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
