replicaCount: 2
nfs:
  server: "${NFS_IP}"
  path: "/volume2/rpi-k3s"
  mountOptions:
    - noatime
  reclaimPolicy: Retain
storageClass:
  defaultClass: false
  onDelete: retain
  pathPattern: "${.PVC.namespace}"
  name: nfs-rpik3s
affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - nfs-subdir-external-provisioner-rpik3s
          topologyKey: kubernetes.io/hostname
