apiVersion: v1
kind: Service
metadata:
  labels:
    app: soulseek
  name: soulseek
  namespace: media
spec:
  selector:
    app: soulseek
  ports:
    - name: "6080"
      protocol: TCP
      port: 6080
      targetPort: 6080
  externalIPs:
    - "${METAL_LB_IP1}"
