apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: soulseek
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: soulseek
  template:
    metadata:
      labels:
        app: soulseek
    spec:
      hostname: soulseek
      initContainers:
        - name: sysctl-setup
          image: busybox
          command:
            [
              "sh",
              "-c",
              "sysctl -w net.ipv4.conf.all.rp_filter=2 && sysctl -w net.ipv6.conf.all.disable_ipv6=1",
            ]
          securityContext:
            privileged: true
        - name: protonwire
          image: ghcr.io/tprasadtp/protonwire:7.3.0-beta1
          restartPolicy: Always
          env:
            - name: WIREGUARD_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: soulseek
                  key: key
            - name: PROTONVPN_SERVER
              value: "CH#71"
            - name: DEBUG
              value: "0"
            - name: KILL_SWITCH
              value: "1"
            # - name: IPCHECK_URL
            #   value: "https://checkip.amazonaws.com/"
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          command: ["/bin/bash", "-c"]
          args:
            [
              "/usr/bin/protonwire connect --container & sleep 10; natpmpc -a 1 0 udp 60 -g 10.2.0.1; natpmpc -a 1 0 tcp 60 -g 10.2.0.1 | grep -oP 'public\\ port\\ \\K\\w+' > /config/protonvpn-port; echo \"Port written to protonvpn-port file\"; cat /config/protonvpn-port; while true; do date; natpmpc -a 1 0 udp 60 -g 10.2.0.1 && natpmpc -a 1 0 tcp 60 -g 10.2.0.1 || { echo -e \"ERROR with natpmpc command \\a\"; break; }; sleep 45; done",
            ]
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
      containers:
        - name: soulseek
          image: realies/soulseek:latest
          env:
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
          ports:
            - containerPort: 6080
          volumeMounts:
            - name: media-config
              mountPath: /data/.SoulseekQt
              subPath: soulseek/data
            - name: media-config
              mountPath: /data/Soulseek Chat Logs
              subPath: soulseek/chat_logs
            - name: media-data
              mountPath: /data/Soulseek Downloads
              subPath: downloads/soulseek
            - name: media-data
              mountPath: /data/Soulseek Shared Folder
              subPath: library/
      dnsPolicy: None
      dnsConfig:
        nameservers: ["1.1.1.1", "1.0.0.1"]
      volumes:
        - name: media-config
          persistentVolumeClaim:
            claimName: media-config
        - name: media-data
          persistentVolumeClaim:
            claimName: media-data
      nodeSelector:
        kubernetes.io/arch: amd64
