apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: soulseek-config
  namespace: media
  labels:
    app: soulseek
    storage.k8s.io/name: nfs
spec:
  storageClassName: nfs-rpik3s
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
