---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: soulseek
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: soulseek
  template:
    metadata:
      labels:
        app: soulseek
    spec:
      hostname: soulseek
      initContainers:
        - name: sysctl-setup
          image: busybox
          command:
            [
              "sh",
              "-c",
              "sysctl -w net.ipv4.conf.all.rp_filter=2 && sysctl -w net.ipv6.conf.all.disable_ipv6=1",
            ]
          securityContext:
            privileged: true # Allow the init container to run with additional privileges
        - name: protonwire
          image: ghcr.io/tprasadtp/protonwire:latest
          restartPolicy: Always
          env:
            - name: WIREGUARD_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: openvpn
                  key: key
            - name: PROTONVPN_SERVER
              value: "IS-NL#1"
            - name: DEBUG
              value: "0"
            - name: KILL_SWITCH
              value: "1"
            - name: IPCHECK_URL
              value: "https://checkip.amazonaws.com/"
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          ports:
            - containerPort: 8000
      containers:
        - name: soulseek
          image: realies/soulseek:latest
          env:
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
          ports:
            - containerPort: 6080
          volumeMounts:
            - name: soulseek-config
              mountPath: /data/.SoulseekQt
              subPath: soulseek/data
            - name: soulseek-config
              mountPath: /data/Soulseek Chat Logs
              subPath: soulseek/chat_logs
            - name: soulseek-data
              mountPath: /data/Soulseek Downloads
              subPath: downloads/soulseek
            - name: soulseek-data
              mountPath: /data/Soulseek Shared Folder
              subPath: library/music
      dnsPolicy: "None"
      dnsConfig:
        nameservers: ["1.1.1.1", "1.0.0.1"]
      volumes:
        - name: soulseek-config
          persistentVolumeClaim:
            claimName: soulseek-config
        - name: soulseek-data
          persistentVolumeClaim:
            claimName: soulseek-data
      nodeSelector:
        kubernetes.io/arch: amd64
