apiVersion: v1
kind: Service
metadata:
  name: soulseek
  namespace: media
  labels:
    app: soulseek
  annotations:
    tailscale.com/hostname: "soulseek"
    tailscale.com/expose: "true"
spec:
  selector:
    app: soulseek
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 6080
