apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: media-tools
  namespace: media
spec:
  hostnames:
  - media.tools
  parentRefs:
  - name: shared-gateway
    namespace: nginx-gateway
    sectionName: media-tools-http
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /sonarr
    backendRefs:
    - name: sonarr
      port: 80
  - matches:
    - path:
        type: PathPrefix
        value: /jackett
    backendRefs:
    - name: jackett
      port: 80
  - matches:
    - path:
        type: PathPrefix
        value: /radarr
    backendRefs:
    - name: radarr
      port: 80
  - matches:
    - path:
        type: Exact
        value: /qbit
    filters:
    - type: RequestRedirect
      requestRedirect:
        path:
          type: ReplaceFullPath
          replaceFullPath: /qbit/
        statusCode: 301
  - matches:
    - path:
        type: PathPrefix
        value: /qbit/
    filters:
    - type: URLRewrite
      urlRewrite:
        path:
          type: ReplacePrefixMatch
          replacePrefixMatch: /
    backendRefs:
    - name: qbittorrent
      port: 80
  - matches:
    - path:
        type: Exact
        value: /soulseek
    filters:
    - type: RequestRedirect
      requestRedirect:
        path:
          type: ReplaceFullPath
          replaceFullPath: /soulseek/
        statusCode: 301
  - matches:
    - path:
        type: PathPrefix
        value: /soulseek/
    filters:
    - type: URLRewrite
      urlRewrite:
        path:
          type: ReplacePrefixMatch
          replacePrefixMatch: /
    backendRefs:
    - name: soulseek
      port: 80
  - matches:
    - path:
        type: Exact
        value: /calibre
    filters:
    - type: RequestRedirect
      requestRedirect:
        path:
          type: ReplaceFullPath
          replaceFullPath: /calibre/
        statusCode: 301
  - matches:
    - path:
        type: PathPrefix
        value: /calibre/
    filters:
    - type: URLRewrite
      urlRewrite:
        path:
          type: ReplacePrefixMatch
          replacePrefixMatch: /
    - type: RequestHeaderModifier
      requestHeaderModifier:
        set:
        - name: X-Script-Name
          value: /calibre
    backendRefs:
    - name: calibre
      port: 80
---
apiVersion: gateway.nginx.org/v1alpha1
kind: ClientSettingsPolicy
metadata:
  name: media-tools-client-settings
  namespace: media
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: media-tools
  body:
    maxSize: "0"
