apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: calibre-media-tools
  namespace: media
spec:
  hostnames:
  - calibre.media.tools
  parentRefs:
  - name: shared-gateway
    namespace: nginx-gateway
    sectionName: calibre-media-tools-http
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: calibre
      port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: media-tools
  namespace: media
spec:
  hostnames:
  - media.tools
  parentRefs:
  - name: shared-gateway
    namespace: nginx-gateway
    sectionName: media-tools-http
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /sonarr
    backendRefs:
    - name: sonarr
      port: 80
  - matches:
    - path:
        type: PathPrefix
        value: /jackett
    backendRefs:
    - name: jackett
      port: 80
  - matches:
    - path:
        type: PathPrefix
        value: /radarr
    backendRefs:
    - name: radarr
      port: 80
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: qbittorrent
      port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: qbt-media-tools
  namespace: media
spec:
  hostnames:
  - qbt.media.tools
  parentRefs:
  - name: shared-gateway
    namespace: nginx-gateway
    sectionName: qbt-media-tools-http
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: qbittorrent
      port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: soulseek-media-tools
  namespace: media
spec:
  hostnames:
  - soulseek.media.tools
  parentRefs:
  - name: shared-gateway
    namespace: nginx-gateway
    sectionName: soulseek-media-tools-http
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: soulseek
      port: 80
---
apiVersion: gateway.nginx.org/v1alpha1
kind: ClientSettingsPolicy
metadata:
  name: media-tools-client-settings
  namespace: media
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: media-tools
  body:
    maxSize: "0"
