apiVersion: v1
kind: ConfigMap
metadata:
 name: qbittorrent-config
 namespace: media
data:
 qBittorrent.conf: |
  [Preferences]
  WebUI\Address=0.0.0.0
  WebUI\ServerDomains=*
  WebUI\HostHeaderValidation=false
  WebUI\Port=9091
  WebUI\LocalHostAuth=false
  WebUI\AuthSubnetWhitelistEnabled=true
  WebUI\AuthSubnetWhitelist=0.0.0.0/0
  Downloads\SavePath=/downloads/complete
  Downloads\TempPath=/downloads/incomplete
  Downloads\PreAllocation=true
  Downloads\UseIncompleteExtension=true
  Downloads\TempPathEnabled=true

  [BitTorrent]
  Session\DefaultSavePath=/downloads/complete
  Session\TempPath=/downloads/incomplete
  Session\TempPathEnabled=true
  Session\AddTorrentPaused=false
  Session\ForceKnownHost=true
---
apiVersion: apps/v1
kind: Deployment
metadata:
 labels:
  app: qbittorrent
 name: qbittorrent
 namespace: media
spec:
 replicas: 1
 strategy:
  type: Recreate
 revisionHistoryLimit: 3
 selector:
  matchLabels:
   app: qbittorrent
 template:
  metadata:
   labels:
    app: qbittorrent
  spec:
   hostname: qbittorrent
   initContainers:
    - name: sysctl-setup
      image: busybox
      command:
       [
        'sh',
        '-c',
        'sysctl -w net.ipv4.conf.all.rp_filter=2 && sysctl -w net.ipv6.conf.all.disable_ipv6=1 && sysctl -w net.ipv4.ip_forward=1',
       ]
      securityContext:
       privileged: true
   containers:
    - name: gluetun
      image: qmcgaw/gluetun:v3.40.0
      securityContext:
       capabilities:
        add:
         - NET_ADMIN
       privileged: true
      env:
       - name: VPN_SERVICE_PROVIDER
         value: protonvpn
       - name: VPN_TYPE
         value: wireguard
       - name: WIREGUARD_PRIVATE_KEY
         valueFrom:
          secretKeyRef:
           name: qbittorrent
           key: key
       - name: WIREGUARD_ENDPOINT_IP
         value: '138.199.6.178'
       - name: SERVER_COUNTRIES
         value: 'Switzerland'
       - name: VPN_PORT_FORWARDING
         value: 'on'
       - name: FIREWALL
         value: 'yes'
       - name: HEALTHCHECK_TARGET
         value: 'ip.me:443'
      ports:
       - containerPort: 9091
         protocol: TCP
      volumeMounts:
       - mountPath: /dev/net/tun
         name: tun-device
      resources:
       requests:
        cpu: 100m
        memory: 256Mi
       limits:
        memory: 256Mi
    - env:
       - name: PUID
         value: '1000'
       - name: PGID
         value: '1000'
       - name: TZ
         value: 'America/New_York'
       - name: WEBUI_PORT
         value: '9091'
      image: linuxserver/qbittorrent:latest
      imagePullPolicy: IfNotPresent
      name: qbittorrent
      resources:
       requests:
        cpu: 800m
        memory: 1Gi
       limits:
        memory: 1Gi
      volumeMounts:
       - mountPath: /config
         name: media-config
         subPath: qbittorrent
       - mountPath: /downloads/incomplete
         name: media-data
         subPath: incomplete/qbittorrent
       - mountPath: /downloads/complete
         name: media-data
         subPath: downloads/qbittorrent
       - mountPath: /config/qBittorrent/qBittorrent.conf
         name: qbittorrent-config-volume
         subPath: qBittorrent.conf
         readOnly: true
   restartPolicy: Always
   dnsPolicy: None
   dnsConfig:
    nameservers: ['1.1.1.1', '1.0.0.1']
   volumes:
    - name: media-config
      persistentVolumeClaim:
       claimName: media-config
    - name: media-data
      persistentVolumeClaim:
       claimName: media-data
    - name: tun-device
      hostPath:
       path: /dev/net/tun
    - name: qbittorrent-config-volume
      configMap:
       name: qbittorrent-config
   nodeSelector:
    kubernetes.io/arch: arm64
