apiVersion: v1
kind: Secret
metadata:
  name: soularr-config
  namespace: media
type: Opaque
stringData:
  config.ini: |
    [Lidarr]
    api_key = ${LIDARR_API_KEY}
    host_url = http://lidarr:80/lidarr
    download_dir = /downloads/soulseek

    [Slskd]
    api_key = ${SLSKD_API_KEY}
    host_url = http://soulseek:80/soulseek
    download_dir = /downloads/soulseek

    [Release Settings]
    use_most_common_tracknum = true
    allow_multi_disc = true
    accepted_countries = Europe,Unknown,US,UK,[Worldwide]
    accepted_formats = CD,Digital Media,Vinyl

    [Search Settings]
    search_timeout = 5000
    maximum_peer_queue = 50
    minimum_peer_upload_speed = 0
    allowed_filetypes = flac,mp3 320,mp3
    search_for_tracks = true
    album_prepend_artist = true
    track_prepend_artist = false
    search_type = incrementing_page
    number_of_albums_to_grab = 5
    remove_wanted_on_failure = false
    minimum_filename_match_ratio = 0.9
    title_blacklist = interview,live,demo,bootleg,compilation,greatest hits,best of
