apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filebrowser
  namespace: filebrowser
  labels:
    app: filebrowser
spec:
  storageClassName: nfs-rpik3s
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 60Gi
