apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filebrowser-ssd
  namespace: filebrowser
  labels:
    app: filebrowser
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 60Gi
