apiVersion: v1
kind: PersistentVolume
metadata:
  name: filebrowser-ssd
  namespace: filebrowser
  labels:
    app: filebrowser
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 60Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/ssd/filebrowser
