apiVersion: apps/v1
kind: Deployment
metadata:
  name: filebrowser
  namespace: filebrowser
  labels:
    app: filebrowser
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filebrowser
  template:
    metadata:
      labels:
        app: filebrowser
    spec:
      containers:
        - name: filebrowser
          image: filebrowser/filebrowser:v2.24.2
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: filebrowser-ssd
              mountPath: /srv
              subPath: files
            - name: filebrowser-ssd
              mountPath: /database.db
              subPath: database.db
            - name: filebrowser-scripts
              mountPath: /scripts
          ports:
            - containerPort: 44301
              protocol: TCP
          resources:
            limits:
              cpu: 2
              memory: 2Gi
            requests:
              cpu: 1
              memory: 1Gi
          command:
            ["/bin/sh", "-c", "/scripts/init-filebrowser.sh"]
      nodeSelector:
        kubernetes.io/arch: arm64
        kubernetes.io/os: linux
      volumes:
        - name: filebrowser-ssd
          persistentVolumeClaim:
            claimName: filebrowser-ssd
        - name: filebrowser-scripts
          configMap:
            name: filebrowser-scripts
            defaultMode: 0755 # Makes files in the volume executable
