apiVersion: v1
kind: ConfigMap
metadata:
  name: filebrowser-scripts
  namespace: filebrowser
  labels:
    app: filebrowser
data:
  init-filebrowser.sh: |
    #!/usr/bin/env sh

    /filebrowser config init
    /filebrowser config set \
        --port 44301 \
        --address 0.0.0.0 \
        --baseurl "/" \
        --root "/srv" \
        --branding.name "🗁" \
        --branding.disableExternal
    /filebrowser users add ${FILEBROWSER_USER} ${FILEBROWSER_PW} --perm.admin
    exec /filebrowser --port 44301 --disable-exec
