apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-ingress-ssd
  labels:
    app: nginx-ingress
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/ssd/nginx-geoip
