apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-ingress-ssd
  namespace: kube-system
  labels:
    app: ninjam-server
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
