---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: filebrowser
  namespace: flux-system
spec:
  image: gtstef/filebrowser
  interval: 30m0s
  exclusionList:
    - "^latest$"
    - "^stable$"
    - "^beta$"
    - "beta"
    - "slim"
    - "webdav"
    - "-private-"
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: unifi-network-application
  namespace: flux-system
spec:
  image: lscr.io/linuxserver/unifi-network-application
  interval: 15m0s
  exclusionList:
    - "^latest$"
    - "^develop"
    - "-ls\\d+$"
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: calibre-web
  namespace: flux-system
spec:
  image: lscr.io/linuxserver/calibre-web
  interval: 15m0s
  exclusionList:
    - "^latest$"
    - "^develop"
    - "-ls\\d+$"
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: radarr
  namespace: flux-system
spec:
  image: linuxserver/radarr
  interval: 30m0s
  exclusionList:
    - "^latest$"
    - "^develop"
    - "^nightly"
    - "-ls\\d+$"
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: sonarr
  namespace: flux-system
spec:
  image: linuxserver/sonarr
  interval: 30m0s
  exclusionList:
    - "^latest$"
    - "^develop"
    - "-ls\\d+$"
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: gluetun
  namespace: flux-system
spec:
  image: qmcgaw/gluetun
  interval: 30m0s
  exclusionList:
    - "^latest$"
    - "^develop"
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: qbittorrent
  namespace: flux-system
spec:
  image: linuxserver/qbittorrent
  interval: 30m0s
  exclusionList:
    - "^latest$"
    - "^develop"
    - "-ls\\d+$"
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: prowlarr
  namespace: flux-system
spec:
  image: linuxserver/prowlarr
  interval: 30m0s
  exclusionList:
    - "^latest$"
    - "^develop"
    - "-ls\\d+$"
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: quixit
  namespace: flux-system
spec:
  image: ghcr.io/ianhundere/quixit
  interval: 5m0s
  secretRef:
    name: ghcr-secret
  exclusionList:
    - "^latest$"
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: tufkin
  namespace: flux-system
spec:
  image: ghcr.io/ianhundere/tufkin
  interval: 5m0s
  secretRef:
    name: ghcr-secret
  exclusionList:
    - "^latest$"
