apiVersion: v1
kind: Secret
metadata:
  name: quixit-credentials
  namespace: quixit
type: Opaque
stringData:
  db-password: ${QUIXIT_PW}
  session-secret: ${QUIXIT_SESSION_SECRET}
  smtp-password: ${TUFKIN_SMTP_PASSWORD}
