apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: radarr
  name: radarr
  namespace: media
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
      containers:
      - env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        image: linuxserver/radarr:arm32v7-version-3.2.2.5080
        imagePullPolicy: IfNotPresent
        name: radarr
        ports:
        - containerPort: 7878
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        volumeMounts:
        - mountPath: /config
          name: media-ssd
          subPath: configs/radarr
        - mountPath: /downloads/transmission
          name: media-ssd
          subPath: downloads/transmission
        - mountPath: /movies
          name: media-ssd
          subPath: library/movies
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
      - name: media-ssd
        persistentVolumeClaim:
          claimName: media-ssd
