apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: radarr
  name: radarr
  namespace: media
spec:
  replicas: 1
  revisionHistoryLimit: 3
  serviceName: radarr
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
      containers:
        - env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          image: linuxserver/radarr:5.3.6
          imagePullPolicy: IfNotPresent
          name: radarr
          ports:
            - containerPort: 7878
              name: http
              protocol: TCP
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              memory: 512Mi
          volumeMounts:
            - mountPath: /config
              name: media-config
              subPath: radarr
            - mountPath: /downloads/complete
              name: media-data
              subPath: downloads/transmission
            - mountPath: /movies
              name: media-data
              subPath: library/movies
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
        - name: media-config
          persistentVolumeClaim:
            claimName: media-config
        - name: media-data
          persistentVolumeClaim:
            claimName: media-data
