apiVersion: v1
kind: Service
metadata:
  labels:
    app: radarr
  name: radarr
  namespace: media
  annotations:
    tailscale.com/hostname: "radarr"
    tailscale.com/expose: "true"
spec:
  type: ClusterIP
  selector:
    app: radarr
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 7878
