apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 namespace: quixit
 name: quixit-data
 labels:
  storage.k8s.io/name: nfs
spec:
 accessModes:
  - ReadWriteOnce
 storageClassName: nfs-rpik3s
 resources:
  requests:
   storage: 20Gi
