apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 name: quixit
 namespace: quixit
 annotations:
  cert-manager.io/cluster-issuer: 'letsencrypt-prod'
  nginx.ingress.kubernetes.io/proxy-body-size: '50m'
  nginx.ingress.kubernetes.io/proxy-connect-timeout: '30'
  nginx.ingress.kubernetes.io/proxy-read-timeout: '1800'
  nginx.ingress.kubernetes.io/proxy-send-timeout: '1800'
spec:
 ingressClassName: nginx
 tls:
  - hosts:
     - '${QUIXIT_HOST}'
    secretName: quixit-tls
 rules:
  - host: '${QUIXIT_HOST}'
    http:
     paths:
      - path: /
        pathType: Prefix
        backend:
         service:
          name: quixit
          port:
           number: 8080
