apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: quixit
 namespace: quixit
 labels:
  app: quixit
spec:
 storageClassName: nfs-rpik3s
 accessModes:
  - ReadWriteMany
 resources:
  requests:
   storage: 60Gi
