apiVersion: v1
kind: Service
metadata:
 name: quixit
 namespace: quixit
spec:
 selector:
  app: quixit
 ports:
  - name: http
    port: 8080
    targetPort: 8080
  - name: frontend
    port: 3000
    targetPort: 8080
  - name: postgres
    port: 5432
    targetPort: 5432
 type: ClusterIP
