apiVersion: v1
kind: ConfigMap
metadata:
 name: quixit-scripts
 namespace: quixit
 labels:
  app: quixit
data:
 init-quixit.sh: |
  #!/usr/bin/env sh
  /filebrowser config init --database /database/filebrowser.db

  /filebrowser config set \
      --database /database/filebrowser.db \
      --port 44301 \
      --address 0.0.0.0 \
      --baseurl "/" \
      --root "/srv" \
      --branding.name "${QUIXIT_HOST}" \
      --branding.disableExternal \
      --branding.files "/branding" \
      --signup

  mkdir -p /srv/SamplePacks/Current
  mkdir -p /srv/SamplePacks/Archive
  echo "Sample directories created"

  /filebrowser users add "${QUIXIT_USER}" "${QUIXIT_PW}" --perm.admin --database /database/filebrowser.db

  # set default permissions for new users
  /filebrowser config set \
      --database /database/filebrowser.db \
      --defaults.scope "/srv/quixit" \
      --defaults.perm.admin=false \
      --defaults.perm.execute=false \
      --defaults.perm.create=true \
      --defaults.perm.rename=false \
      --defaults.perm.modify=false \
      --defaults.perm.delete=false \
      --defaults.perm.share=false \
      --defaults.perm.download=true

  exec /filebrowser --port 44301 --database /database/filebrowser.db --disable-exec
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: quixit
 namespace: quixit
 labels:
  app: quixit
spec:
 replicas: 1
 revisionHistoryLimit: 3
 strategy:
  type: RollingUpdate
 selector:
  matchLabels:
   app: quixit
 template:
  metadata:
   labels:
    app: quixit
  spec:
   containers:
    - name: quixit
      image: filebrowser/filebrowser:v2.32.0
      imagePullPolicy: IfNotPresent
      volumeMounts:
       - name: quixit
         mountPath: /srv
         subPath: files
       - name: quixit
         mountPath: /database
         subPath: database
       - name: quixit
         mountPath: /branding
         subPath: branding
       - name: quixit-scripts
         mountPath: /scripts
      ports:
       - name: http
         containerPort: 44301
         protocol: TCP
      resources:
       requests:
        cpu: 500m
        memory: 512Mi
       limits:
        memory: 512Mi
      command: ['/bin/sh', '-c', '/scripts/init-quixit.sh']
   volumes:
    - name: quixit
      persistentVolumeClaim:
       claimName: quixit
    - name: quixit-scripts
      configMap:
       name: quixit-scripts
       defaultMode: 0755
