apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 namespace: quixit
 name: quixit
 annotations:
  cert-manager.io/cluster-issuer: letsencrypt-prod
  cert-manager.io/issue-temporary-certificate: 'true'
  acme.cert-manager.io/http01-edit-in-place: 'true'
  nginx.ingress.kubernetes.io/proxy-body-size: 50m
  nginx.ingress.kubernetes.io/limit-connections: "20"
  nginx.ingress.kubernetes.io/limit-rpm: "60"
  nginx.ingress.kubernetes.io/limit-burst-multiplier: "3"
  nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
  nginx.ingress.kubernetes.io/ssl-redirect: 'true'
  nginx.ingress.kubernetes.io/configuration-snippet: |
   more_set_headers "Strict-Transport-Security: max-age=31536000; includeSubDomains; preload";
   more_set_headers "server: hide";
   more_set_headers "X-Frame-Options: DENY";
   more_set_headers "X-Content-Type-Options: nosniff";
   more_set_headers "Referrer-Policy: strict-origin-when-cross-origin";
   more_set_headers "Permissions-Policy: camera=(), microphone=(), geolocation=()";
   more_set_headers "Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'self'";
  nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
  nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
  nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
  nginx.ingress.kubernetes.io/proxy-buffer-size: "8k"
  nginx.ingress.kubernetes.io/enable-cors: "true"
  nginx.ingress.kubernetes.io/cors-allow-methods: "GET, PUT, POST, DELETE, PATCH, OPTIONS"
  nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization"
  nginx.ingress.kubernetes.io/whitelist-source-range: "${ALLOWED_IP_RANGES}"
spec:
 ingressClassName: nginx
 tls:
  - hosts:
     - ${QUIXIT_HOST}
    secretName: quixit-cert
 rules:
  - host: ${QUIXIT_HOST}
    http:
     paths:
      - path: /
        pathType: Prefix
        backend:
         service:
          name: quixit
          port:
           number: 44301
