apiVersion: apps/v1
kind: Deployment
metadata:
  name: ha
  namespace: ha
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ha
  template:
    metadata:
      labels:
        app: ha
    spec:
      dnsPolicy: ClusterFirst
      containers:
        - name: ha
          image: ghcr.io/home-assistant/home-assistant:2023.11.2
          imagePullPolicy: Always
          securityContext:
            privileged: true
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 750m
              memory: 512Mi
              rpi-k3s/zwave: 1
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: America/NewYork
            - name: VERSION
              value: docker
          ports:
            - containerPort: 8123
              hostPort: 8123
              protocol: TCP
          volumeMounts:
            - name: ha
              mountPath: /config
            - mountPath: /dev/zwave
              name: zwavestick
      volumes:
        - name: ha
          persistentVolumeClaim:
            claimName: ha
        - name: zwavestick
          hostPath:
            path: /dev/serial/by-id/usb-Zooz_800_Z-Wave_Stick_533D004242-if00
