apiVersion: apps/v1
kind: Deployment
metadata:
  name: ha
  namespace: ha
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ha
  template:
    metadata:
      labels:
        app: ha
    spec:
      dnsPolicy: ClusterFirst
      initContainers:
        - name: zwave
          restartPolicy: Always
          image: zwavejs/zwave-js-ui:9.3.2
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: true
            privileged: true
          resources:
            requests:
              cpu: 500m
              memory: 256Mi
            limits:
              cpu: 1
              memory: 512Mi
              # rpi-k3s/zwave: 1
          env:
            - name: TZ
              value: America/NewYork
            - name: SESSION_SECRET
              value: "A59E88FBDD4A10D7E1925C755F3237B1"
            - name: ZWAVEJS_EXTERNAL_CONFIG
              value: /usr/src/app/store/.config-db
          ports:
            - containerPort: 8091
              name: http
              protocol: TCP
            - containerPort: 3000
              name: websockets
              protocol: TCP
          volumeMounts:
            - mountPath: /usr/src/app/store
              subPath: zwave
              name: ha
            - mountPath: /dev/zwave
              name: zwavestick
      containers:
        - name: ha
          image: ghcr.io/home-assistant/home-assistant:2023.11.2
          imagePullPolicy: Always
          securityContext:
            privileged: true
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 750m
              memory: 512Mi
              # rpi-k3s/zwave: 1
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: America/NewYork
            - name: VERSION
              value: docker
          ports:
            - containerPort: 8123
              hostPort: 8123
              protocol: TCP
          volumeMounts:
            - name: ha
              mountPath: /config
            - mountPath: /dev/zwave
              name: zwavestick
      volumes:
        - name: ha
          persistentVolumeClaim:
            claimName: ha
        - name: zwavestick
          hostPath:
            path: /dev/serial/by-id/usb-Zooz_800_Z-Wave_Stick_533D004242-if00
