apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: ha
 namespace: ha
 labels:
  app: ha
spec:
 storageClassName: nfs-rpik3s
 accessModes:
  - ReadWriteMany
 resources:
  requests:
   storage: 60Gi
