apiVersion: v1
kind: Service
metadata:
 name: ha
 namespace: ha
spec:
 type: ClusterIP
 selector:
  app: ha
 ports:
  - name: ha
    protocol: TCP
    port: 8123
    targetPort: 8123
 externalIPs:
  - '${METAL_LB_IP1}'
