apiVersion: v1
kind: Service
metadata:
  name: ha
  namespace: ha
spec:
  type: ClusterIP
  selector:
    app: ha
  ports:
    - name: ha
      port: 8123
      targetPort: 8123
    - name: zwave-http
      port: 8091
      targetPort: 8091
    - name: zwave-websockets
      port: 3000
      targetPort: 3000
  externalIPs:
    - "${METAL_LB_IP1}"
