apiVersion: apps/v1
kind: Deployment
metadata:
  name: zwave
  namespace: ha
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: zwave
  template:
    metadata:
      labels:
        app: zwave
    spec:
      containers:
        - name: zwave
          image: zwavejs/zwave-js-ui:9.3.2
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: true
            privileged: true
          resources:
            requests:
              cpu: 500m
              memory: 256Mi
            limits:
              cpu: 1
              memory: 512Mi
              rpi-k3s/zwave: 1
          env:
            - name: TZ
              value: America/NewYork
            - name: SESSION_SECRET
              value: "A59E88FBDD4A10D7E1925C755F3237B1"
            - name: ZWAVEJS_EXTERNAL_CONFIG
              value: /usr/src/app/store/.config-db
          ports:
            - containerPort: 8091
              name: http
              protocol: TCP
            - containerPort: 3000
              name: websockets
              protocol: TCP
          volumeMounts:
            - mountPath: /usr/src/app/store
              subPath: zwave
              name: zwave
            - mountPath: /dev/zwave
              name: zwavestick
      volumes:
        - name: zwave
          persistentVolumeClaim:
            claimName: ha
        - name: zwavestick
          hostPath:
            path: /dev/serial/by-id/usb-Zooz_800_Z-Wave_Stick_533D004242-if00
