apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: media
  name: music-data
  labels:
    storage.k8s.io/name: nfs
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-music
  resources:
    requests:
      storage: 80Gi
