replicaCount: 1

image:
  repository: "linuxserver/radarr"
  tag: arm32v7-3.0.1.4259-ls91
  pullPolicy: IfNotPresent

env:
  - name: PUID
    value: "1000"
  - name: PGID
    value: "1000"

service:
  type: ClusterIP
  port: 80

volumes:
  - name: "media-ssd"
    persistentVolumeClaim:
      claimName: "media-ssd"

volumeMounts:
  - name: "media-ssd"
    mountPath: "/config"
    subPath: "configs/radarr"
  - name: "media-ssd"
    mountPath: "/downloads/transmission"
    subPath: "downloads/transmission"
  - name: media-ssd
    mountPath: "/movies"
    subPath: "library/movies"
