apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: media
  name: media-data
  labels:
    storage.k8s.io/name: nfs
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-video
  resources:
    requests:
      storage: 6.5Ti
