claimToken: "claim-x8Txb8YiYSwHaa3syxog"

image:
  repository: linuxserver/plex
  tag: arm32v7-latest
  pullPolicy: IfNotPresent

kubePlex:
  enabled: false

timezone: America/New_York

service:
  type: LoadBalancer # We will use a LoadBalancer to obtain a virtual IP that can be exposed to Plex Media via our router
  port: 32400 # Port to expose Plex

nodeSelector:
  beta.kubernetes.io/arch: arm
  beta.kubernetes.io/os: linux
