---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "boob"
  labels:
    type: "local"
spec:
  storageClassName: "manual"
  capacity:
    storage: "1Gi"
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/ssd/boob"
