---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: "media"
  name: "boob"
spec:
  storageClassName: "manual"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "1Gi"
