replicaCount: 1

image:
  repository: linuxserver/sonarr
  tag: arm32v7-2.0.0.5344-ls92
  pullPolicy: IfNotPresent

env:
  - name: PUID
    value: "1000"
  - name: PGID
    value: "1000"

service:
  type: ClusterIP
  port: 80

volumes:
  - name: media-ssd
    persistentVolumeClaim:
      claimName: "media-ssd"

volumeMounts:
  - name: media-ssd
    mountPath: "/config"
    subPath: "configs/sonarr"
  - name: media-ssd
    mountPath: "/downloads/transmission"
    subPath: "downloads/transmission"
  - name: media-ssd
    mountPath: "/tv"
    subPath: "library/tv"
