claimToken: ""

image:
  repository: linuxserver/plex
  tag: version-1.23.2.4656-85f0adf5b
  pullPolicy: IfNotPresent

kubePlex:
  enabled: false

timezone: America/New_York

service:
  type: LoadBalancer
  port: 32400

nodeSelector:
  beta.kubernetes.io/arch: arm
  beta.kubernetes.io/os: linux
