apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: media
  name: hdd
  labels:
    storage.k8s.io/name: nfs
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 5Ti