apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: media
  name: media-config
  labels:
    storage.k8s.io/name: nfs
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-rpik3s
  resources:
    requests:
      storage: 400Gi
