apiVersion: v1
kind: Service
metadata:
  labels:
    app: sonarr
  name: sonarr
  namespace: media
  annotations:
    tailscale.com/hostname: "sonarr"
    tailscale.com/expose: "true"
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8989
  selector:
    app: sonarr
  type: ClusterIP
