image:
  repository: registry.k8s.io/sig-storage/nfs-subdir-external-provisioner
  tag: v4.0.2
  pullPolicy: IfNotPresent
replicaCount: 1
leaderElection:
  enabled: false
nfs:
  server: "${NFS_IP}"
  path: "/volume2/music"
  mountOptions:
    - nfsvers=4.1
    - hard
    - timeo=600
    - retrans=3
    - proto=tcp
    - rsize=4096
    - wsize=4096
    - noatime
    - nodiratime
  reclaimPolicy: Retain
storageClass:
  defaultClass: false
  onDelete: retain
  pathPattern: "./"
  name: nfs-music
affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - nfs-subdir-external-provisioner-music
          topologyKey: kubernetes.io/hostname
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    memory: 128Mi
