apiVersion: apps/v1
kind: Deployment
metadata:
 name: oauth2-proxy
 namespace: quixit
 labels:
  app: oauth2-proxy
spec:
 replicas: 1
 selector:
  matchLabels:
   app: oauth2-proxy
 template:
  metadata:
   labels:
    app: oauth2-proxy
  spec:
   containers:
    - name: oauth2-proxy
      image: quay.io/oauth2-proxy/oauth2-proxy:v7.4.0
      args:
       - --provider=github
       - --email-domain=*
       - --upstream=file:///dev/null
       - --http-address=0.0.0.0:4180
       - --cookie-secret=$(COOKIE_SECRET)
       - --client-id=$(GITHUB_CLIENT_ID)
       - --client-secret=$(GITHUB_CLIENT_SECRET)
       - --redirect-url=https://$(QUIXIT_HOST)/auth/github/callback
       - --cookie-secure=true
       - --pass-access-token=true
       - --set-xauthrequest=true
       - --skip-provider-button=true
       - --cookie-domain=$(QUIXIT_HOST)
       - --request-logging=true
       - --standard-logging=true
       - --auth-logging=true
       - --insecure-oidc-allow-unverified-email=true
       - --skip-jwt-bearer-tokens=true
       - --ssl-insecure-skip-verify=true
      env:
       - name: OAUTH2_PROXY_SSL_INSECURE_SKIP_VERIFY
         value: 'true'
       - name: COOKIE_SECRET
         valueFrom:
          secretKeyRef:
           name: quixit-cookie
           key: secret
       - name: GITHUB_CLIENT_ID
         valueFrom:
          secretKeyRef:
           name: quixit-github
           key: client_id
       - name: GITHUB_CLIENT_SECRET
         valueFrom:
          secretKeyRef:
           name: quixit-github
           key: client_secret
       - name: QUIXIT_HOST
         valueFrom:
          configMapKeyRef:
           name: quixit-config
           key: quixit_host
      ports:
       - containerPort: 4180
         protocol: TCP
      resources:
       requests:
        cpu: 100m
        memory: 128Mi
       limits:
        memory: 256Mi
