## Official nextcloud image version
## ref: https://hub.docker.com/r/library/nextcloud/tags/
##
image:
  repository: nextcloud
  tag: 21.0.0-apache
  pullPolicy: IfNotPresent
replicaCount: 1
nextcloud:
  host: nextcloud.clusterian.pw
  username: %NEXTCLOUD_USER%
  password: %NEXTCLOUD_PASSWORD%
  update: 0
  datadir: /var/www/html/data
service:
  type: ClusterIP
  port: 8080
  loadBalancerIP: nil
  nodePort: nil
  selector:
    app: nextcloud-ingress
  externalIPs:
    - "192.168.3.240"
persistence:
  enabled: true
  existingClaim: nextcloud-ssd
  accessMode: ReadWriteOnce
  size: 60Gi
resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi
livenessProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 15
  timeoutSeconds: 5
  failureThreshold: 3
  successThreshold: 1
readinessProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 15
  timeoutSeconds: 5
  failureThreshold: 3
  successThreshold: 1
