apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-ssd
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 60Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/ssd/nextcloud
---
