apiVersion: batch/v1
kind: Job
metadata:
 name: quixit-to-songs
 namespace: quixit
spec:
 template:
  spec:
   containers:
    - name: quixit-to-songs
      image: filebrowser/filebrowser:v2.32.0
      command:
       - /bin/sh
       - -c
       - |
        # get current quixit number
        if [ -f "/srv/quixit/current_quixit_number.txt" ]; then
          QUIXIT_NUMBER=$(cat /srv/quixit/current_quixit_number.txt)
          QUIXIT_DIR="/srv/quixit/quixit-$QUIXIT_NUMBER"
        else
          exit 1
        fi

        # check if in samples phase
        if ls "$QUIXIT_DIR/QUIXIT_HAS_BEGUN_UPLOAD_SAMPLES_BEFORE_"* 1>/dev/null 2>&1; then
          # remove samples phase indicator
          rm "$QUIXIT_DIR/QUIXIT_HAS_BEGUN_UPLOAD_SAMPLES_BEFORE_"*
          
          # set deadline (7 days)
          SONG_DEADLINE=$(date -d "7 days" +%Y-%m-%d 2>/dev/null || date -v+7d +%Y-%m-%d 2>/dev/null || echo "$(date +%Y-%m-%d)")
          
          # create songs phase indicator
          echo "upload your songs to the songs directory before $SONG_DEADLINE" > "$QUIXIT_DIR/SUBMIT_SONGS_BEFORE_$SONG_DEADLINE.txt"
          
          # create sample pack
          cd "$QUIXIT_DIR"
          tar -czf SAMPLE_PACK.tar.gz samples/
        else
          exit 1
        fi
      volumeMounts:
       - name: quixit
         mountPath: /srv
         subPath: files
   volumes:
    - name: quixit
      persistentVolumeClaim:
       claimName: quixit
   restartPolicy: OnFailure
