apiVersion: batch/v1
kind: Job
metadata:
 name: quixit-to-songs
 namespace: quixit
spec:
 template:
  spec:
   containers:
    - name: quixit-to-songs
      image: alpine:3.21.3
      command:
       - /bin/sh
       - -c
       - |
        # get current quixit number
        if [ -f "/srv/quixit/current_quixit_number.txt" ]; then
          QUIXIT_NUMBER=$(cat /srv/quixit/current_quixit_number.txt)
          QUIXIT_DIR="/srv/quixit/quixit-$QUIXIT_NUMBER"
        else
          exit 1
        fi

        # check if in samples phase
        if ls "$QUIXIT_DIR/QUIXIT_HAS_BEGUN_UPLOAD_SAMPLES_BEFORE_"* 1>/dev/null 2>&1; then
          # remove samples phase indicator files
          rm "$QUIXIT_DIR/QUIXIT_HAS_BEGUN_UPLOAD_SAMPLES_BEFORE_"*
          
          # set deadline (7 days) using manual calculation that works in all environments
          TODAY=$(date +%Y-%m-%d)
          YEAR=$(echo $TODAY | cut -d'-' -f1)
          MONTH=$(echo $TODAY | cut -d'-' -f2)
          DAY=$(echo $TODAY | cut -d'-' -f3)
          
          # Remove leading zeros
          MONTH=$(echo $MONTH | sed 's/^0//')
          DAY=$(echo $DAY | sed 's/^0//')
          
          # Add 14 days
          DAY=$((DAY + 14))
          
          # Handle month rollover
          DAYS_IN_MONTH=31
          if [ "$MONTH" = "4" ] || [ "$MONTH" = "6" ] || [ "$MONTH" = "9" ] || [ "$MONTH" = "11" ]; then
            DAYS_IN_MONTH=30
          elif [ "$MONTH" = "2" ]; then
            # Check for leap year
            if [ $((YEAR % 4)) -eq 0 ] && [ $((YEAR % 100)) -ne 0 ] || [ $((YEAR % 400)) -eq 0 ]; then
              DAYS_IN_MONTH=29
            else
              DAYS_IN_MONTH=28
            fi
          fi
          
          # Adjust for month rollover
          if [ "$DAY" -gt "$DAYS_IN_MONTH" ]; then
            DAY=$((DAY - DAYS_IN_MONTH))
            MONTH=$((MONTH + 1))
            
            # Adjust for year rollover
            if [ "$MONTH" -gt 12 ]; then
              MONTH=1
              YEAR=$((YEAR + 1))
            fi
          fi
          
          # Format with padding
          if [ "$MONTH" -lt 10 ]; then
            MONTH="0$MONTH"
          fi
          if [ "$DAY" -lt 10 ]; then
            DAY="0$DAY"
          fi
          
          SONG_DEADLINE="$YEAR-$MONTH-$DAY"
          
          # create songs phase indicator file with detailed information
          echo "QUIXIT #$QUIXIT_NUMBER - SONG SUBMISSION PHASE" > "$QUIXIT_DIR/SUBMIT_SONGS_BEFORE_$SONG_DEADLINE.txt"
          echo "" >> "$QUIXIT_DIR/SUBMIT_SONGS_BEFORE_$SONG_DEADLINE.txt"
          echo "Upload your finished track before: $SONG_DEADLINE" >> "$QUIXIT_DIR/SUBMIT_SONGS_BEFORE_$SONG_DEADLINE.txt"
          echo "" >> "$QUIXIT_DIR/SUBMIT_SONGS_BEFORE_$SONG_DEADLINE.txt"
          echo "Accepted file formats: .wav, .mp3, .ogg, .flac, .aiff" >> "$QUIXIT_DIR/SUBMIT_SONGS_BEFORE_$SONG_DEADLINE.txt"
          echo "" >> "$QUIXIT_DIR/SUBMIT_SONGS_BEFORE_$SONG_DEADLINE.txt"
          echo "Guidelines:" >> "$QUIXIT_DIR/SUBMIT_SONGS_BEFORE_$SONG_DEADLINE.txt"
          echo "- Upload your finished track to the 'songs' directory" >> "$QUIXIT_DIR/SUBMIT_SONGS_BEFORE_$SONG_DEADLINE.txt"
          echo "- Use ONLY samples from the provided sample pack" >> "$QUIXIT_DIR/SUBMIT_SONGS_BEFORE_$SONG_DEADLINE.txt"
          echo "- Bonus: Use ALL samples from the provided sample pack" >> "$QUIXIT_DIR/SUBMIT_SONGS_BEFORE_$SONG_DEADLINE.txt"
          echo "" >> "$QUIXIT_DIR/SUBMIT_SONGS_BEFORE_$SONG_DEADLINE.txt"
          echo "- IMPORTANT: When uploading a finished track, include username exactly as registered, case sensitive; for example, 'mytrack_UserName.mp3', note the underscore immediately precedes the username." >> "$QUIXIT_DIR/SUBMIT_SONGS_BEFORE_$SONG_DEADLINE.txt"
          echo "" >> "$QUIXIT_DIR/SUBMIT_SONGS_BEFORE_$SONG_DEADLINE.txt"
          echo "After the deadline, all tracks will be compiled into a downloadable archive." >> "$QUIXIT_DIR/SUBMIT_SONGS_BEFORE_$SONG_DEADLINE.txt"
          
          # update current quixit number file
          echo "$QUIXIT_NUMBER" > "/srv/quixit/current_quixit_number.txt"
          chmod 444 "/srv/quixit/current_quixit_number.txt"
          
          # create songs directory for uploading songs
          mkdir -p "$QUIXIT_DIR/songs"
          chmod 777 "$QUIXIT_DIR/songs"
          
          # create sample pack
          SAMPLES_FOLDER="$QUIXIT_DIR/samples"
          echo "Creating sample pack from $SAMPLES_FOLDER"
          SAMPLE_COUNT=$(find "$SAMPLES_FOLDER" -type f | wc -l)
          echo "Found $SAMPLE_COUNT samples to pack"

          if [ -d "$SAMPLES_FOLDER" ] && [ "$SAMPLE_COUNT" -gt 0 ]; then
            echo "Files to be included in sample pack:"
            find "$SAMPLES_FOLDER" -type f -print # print absolute paths for clarity
            (cd "$SAMPLES_FOLDER" && tar -czvf "../SAMPLE_PACK.tar.gz" .)
            if [ $? -ne 0 ]; then
                echo "Error: Failed to create sample pack"
                # exit 1 # decide on error handling
            else
                # verify the archive was created and contains files
                if [ ! -s "$QUIXIT_DIR/SAMPLE_PACK.tar.gz" ]; then
                    echo "Error: Sample pack is empty or was not created"
                    # exit 1 # decide on error handling
                else
                    echo "Verifying sample pack contents:"
                    tar -tvf "$QUIXIT_DIR/SAMPLE_PACK.tar.gz"
                    ARCHIVE_COUNT=$(tar -tvf "$QUIXIT_DIR/SAMPLE_PACK.tar.gz" | grep -v "/$" | wc -l)
                    echo "Archive contains $ARCHIVE_COUNT files"
                    # remove samples directory after creating sample pack
                    if [ "$ARCHIVE_COUNT" -gt 0 ]; then # only remove if archive has content
                        echo "Sample pack created successfully, removing samples folder"
                        rm -rf "$SAMPLES_FOLDER"
                    else
                        echo "Warning: Sample pack is empty or verification failed, keeping samples folder"
                        # exit 1 # decide on error handling
                    fi
                fi
            fi
          elif [ "$SAMPLE_COUNT" -eq 0 ]; then
            echo "No samples found in $SAMPLES_FOLDER to pack. Extending sample phase by 7 days is handled by cronjob, this job will not create an empty pack."
            # If no samples, this job effectively does nothing further with sample packing.
            # The cronjob quixit-phase-checker handles extending the sample phase if no samples are found at deadline.
            # We might want to reconsider if this manual job should also create an empty pack or have different logic.
            # For now, it will just not create the pack and not remove the samples folder.
          else
            echo "Samples directory $SAMPLES_FOLDER does not exist."
            # exit 1 # decide on error handling
          fi
        else
          echo "Error: Not in samples phase or no phase indicator file found for Quixit #$QUIXIT_NUMBER"
          exit 1
        fi
      volumeMounts:
       - name: quixit
         mountPath: /srv
         subPath: files
   volumes:
    - name: quixit
      persistentVolumeClaim:
       claimName: quixit
   restartPolicy: OnFailure
