image:
  repository: tailscale/tailscale
  pullPolicy: IfNotPresent
  tag: v1.66.4@sha256:8c80cf92bfbc6938d05826b1aee899e629b231cecf7921bd1d72a4150e71e3f3
oauth:
  clientId: "${TS_CLIENT_ID}"
  clientSecret: "${TS_CLIENT_SECRET}"
apiServerProxyConfig:
  mode: "true"
