apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jackett
  name: jackett
  namespace: media
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: jackett
  template:
    metadata:
      labels:
        app: jackett
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - arm64
      hostname: jackett
      initContainers:
        - name: sysctl-setup
          image: busybox
          command:
            [
              "sh",
              "-c",
              "sysctl -w net.ipv4.conf.all.rp_filter=2 && sysctl -w net.ipv6.conf.all.disable_ipv6=1",
            ]
          securityContext:
            privileged: true
        - name: protonwire
          image: ghcr.io/tprasadtp/protonwire:7.3.0-beta2
          restartPolicy: Always
          env:
            - name: WIREGUARD_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: jackett
                  key: key
            - name: PROTONVPN_SERVER
              value: "CH-NL#1"
            - name: DEBUG
              value: "0"
            - name: KILL_SWITCH
              value: "1"
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
      containers:
        - env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          image: linuxserver/jackett:0.21.1145
          imagePullPolicy: IfNotPresent
          name: jackett
          ports:
            - containerPort: 9117
              name: http
              protocol: TCP
          resources:
            requests:
              cpu: 500m
              memory: 320Mi
          volumeMounts:
            - mountPath: /config
              name: media-config
              subPath: jackett
      dnsPolicy: None
      dnsConfig:
        nameservers: ["1.1.1.1", "1.0.0.1"]
      restartPolicy: Always
      volumes:
        - name: media-config
          persistentVolumeClaim:
            claimName: media-config
