apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jackett
  name: jackett
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jackett
  template:
    metadata:
      labels:
        app: jackett
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - transmission-openvpn
                topologyKey: kubernetes.io/hostname
      containers:
        - env:
            - name: VPN_ENABLED
              value: "yes"
            - name: VPN_TYPE
              value: "openvpn"
            - name: VPN_USERNAME
              valueFrom:
                secretKeyRef:
                  key: username
                  name: openvpn
            - name: VPN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: openvpn
            - name: LAN_NETWORK
              value: "${CIDR}"
            - name: CREATE_TUN_DEVICE
              value: "true" # Needed for VPN
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          image: zfigz/docker-jackettvpn:v0.0.4
          imagePullPolicy: IfNotPresent
          name: jackett
          livenessProbe:
            failureThreshold: 6
            initialDelaySeconds: 5
            periodSeconds: 15
            successThreshold: 1
            httpGet:
              path: /health
              port: http
            timeoutSeconds: 10
          readinessProbe:
            failureThreshold: 6
            initialDelaySeconds: 5
            timeoutSeconds: 10
            periodSeconds: 15
            successThreshold: 1
            httpGet:
              path: /health
              port: http
          startupProbe:
            failureThreshold: 6
            initialDelaySeconds: 30
            timeoutSeconds: 10
            periodSeconds: 10
            successThreshold: 1
            httpGet:
              path: /health
              port: http
          ports:
            - containerPort: 9117
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: 800m
              memory: 256Mi
            requests:
              cpu: 400m
              memory: 128Mi
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          volumeMounts:
            - mountPath: /config
              name: media-ssd
              subPath: configs/jackett
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
        - name: media-ssd
          persistentVolumeClaim:
            claimName: media-ssd
        - name: dev-tun
          hostPath: # Needed for VPN
            path: /dev/net/tun
            type: ""
      nodeSelector:
        kubernetes.io/arch: arm64
        kubernetes.io/os: linux
