apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kube-plex
  name: plex-kube-plex
  namespace: media
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: kube-plex
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: kube-plex
    spec:
      restartPolicy: Always
      containers:
        - env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: America/New_York
            - name: PLEX_CLAIM
              value: "${PLEX_CLAIM}"
            - name: PMS_INTERNAL_ADDRESS
              value: http://plex-kube-plex:32400
            - name: PMS_IMAGE
              value: linuxserver/plex:arm32v7-1.25.2
            - name: KUBE_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: TRANSCODE_PVC
              value: plex-kube-plex-transcode
            - name: DATA_PVC
              value: plex-kube-plex-data
            - name: CONFIG_PVC
              value: plex-kube-plex-config
          name: plex
          image: linuxserver/plex:arm32v7-1.25.6
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 32400
              name: pms
              protocol: TCP
            - containerPort: 32400
              name: http
              protocol: TCP
            - containerPort: 32443
              name: https
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /identity
              port: 32400
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /identity
              port: 32400
              scheme: HTTP
            initialDelaySeconds: 15
            timeoutSeconds: 5
          resources:
            requests:
              cpu: 2
              memory: 2Gi
              ephemeral-storage: 2Gi
            limits:
              cpu: 4
              memory: 4Gi
              ephemeral-storage: 4Gi
          volumeMounts:
            - mountPath: /library
              name: media-hdd
              subPath: library
            - mountPath: /config
              name: media-ssd
              subPath: plex/config
            - mountPath: /transcode
              name: media-ssd
              subPath: plex/transcode
            - mountPath: /shared
              name: shared
      volumes:
        - name: media-ssd
          persistentVolumeClaim:
            claimName: media-ssd
        - name: media-hdd
          persistentVolumeClaim:
            claimName: hdd
        - emptyDir: {}
          name: shared
      dnsPolicy: ClusterFirst
      hostname: plex-kube-plex
      nodeSelector:
        beta.kubernetes.io/arch: arm
        beta.kubernetes.io/os: linux
