apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kube-plex
  name: plex-kube-plex
  namespace: media
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: kube-plex
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: kube-plex
    spec:
      restartPolicy: Always
      containers:
        - env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: America/New_York
            - name: PLEX_CLAIM
              value: "${PLEX_CLAIM}"
            - name: PMS_INTERNAL_ADDRESS
              value: http://plex-kube-plex:32400
            - name: DATA_PVC
              value: plex-kube-plex-data
            - name: CONFIG_PVC
              value: plex-kube-plex-config
          name: plex
          image: linuxserver/plex:1.28.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 32400
              name: pms
              protocol: TCP
            - containerPort: 32400
              name: http
              protocol: TCP
            - containerPort: 32443
              name: https
              protocol: TCP
          startupProbe:
            failureThreshold: 30
            initialDelaySeconds: 5
            timeoutSeconds: 10
            periodSeconds: 10
            successThreshold: 1
            httpGet:
              path: /identity
              port: 32400
          livenessProbe:
            httpGet:
              path: /identity
              port: 32400
            successThreshold: 1
            failureThreshold: 5
            initialDelaySeconds: 30
            timeoutSeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /identity
              port: 32400
            successThreshold: 1
            failureThreshold: 5
            initialDelaySeconds: 30
            timeoutSeconds: 10
            periodSeconds: 10
          resources:
            requests:
              cpu: 2
              memory: 2Gi
            limits:
              cpu: 4
              memory: 7.5Gi
          volumeMounts:
            - mountPath: /library
              name: media-hdd
              subPath: library
            - mountPath: /config
              name: media-ssd
              subPath: plex/config
            - mountPath: /shared
              name: shared
      volumes:
        - name: media-ssd
          persistentVolumeClaim:
            claimName: media-ssd
        - name: media-hdd
          persistentVolumeClaim:
            claimName: hdd
        - emptyDir: {}
          name: shared
      dnsPolicy: ClusterFirst
      hostname: plex-kube-plex
      nodeSelector:
        kubernetes.io/arch: amd64
        kubernetes.io/os: linux
