apiVersion: v1
kind: Service
metadata:
  labels:
    app: plex
  name: plex
  namespace: media
status:
  loadBalancer:
    ingress:
      - ip: "${METAL_LB_IP2}"
spec:
  selector:
    app: plex
  externalTrafficPolicy: Cluster
  type: LoadBalancer
  ports:
    - name: pms
      nodePort: 32081
      port: 32400
      protocol: TCP
      targetPort: pms
    - name: http
      nodePort: 32178
      port: 80
      protocol: TCP
      targetPort: pms
    - name: https
      nodePort: 32296
      port: 443
      protocol: TCP
      targetPort: 32443
