apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kube-plex
  name: plex-kube-plex
  namespace: media
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: kube-plex
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: kube-plex
    spec:
      containers:
        - env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: America/New_York
            - name: PLEX_CLAIM
              value: ""
            - name: PMS_INTERNAL_ADDRESS
              value: http://plex-kube-plex:32400
            - name: PMS_IMAGE
              value: linuxserver/plex:version-1.23.2.4656-85f0adf5b
            - name: KUBE_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: TRANSCODE_PVC
              value: plex-kube-plex-transcode
            - name: DATA_PVC
              value: plex-kube-plex-data
            - name: CONFIG_PVC
              value: plex-kube-plex-config
          image: linuxserver/plex:version-1.23.2.4656-85f0adf5b
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /identity
              port: 32400
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          name: plex
          ports:
            - containerPort: 32400
              name: pms
              protocol: TCP
            - containerPort: 32400
              name: http
              protocol: TCP
            - containerPort: 32443
              name: https
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /identity
              port: 32400
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /library
              name: media-ssd
              subPath: library
            - mountPath: /config
              name: media-ssd
              subPath: plex/config
            - mountPath: /transcode
              name: media-ssd
              subPath: plex/transcode
            - mountPath: /shared
              name: shared
      dnsPolicy: ClusterFirst
      hostname: plex-kube-plex
      nodeSelector:
        beta.kubernetes.io/arch: arm
        beta.kubernetes.io/os: linux
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
        - name: media-ssd
          persistentVolumeClaim:
            claimName: media-ssd
        - emptyDir: {}
          name: shared
