apiVersion: ENC[AES256_GCM,data:OJk=,iv:yecMJmPiaoIXBqT8b3jRypWC2Q3KaosjRMGRCad8rlc=,tag:N762nX6Vmk0UoRaaXIMSmg==,type:str]
kind: ENC[AES256_GCM,data:3AkN2F27,iv:MBssWzxmx3vPEPqcF0rAZ84HUgAJ2syu3wd0f51LDdY=,tag:siV1NU9kqoCfW+rlL/N5Bg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:KgHsYb+p7cmced+6nF7I,iv:eBXrxScNYivTw9IEWAkAK8rCMzHUIU+adXhx9hqU9ZE=,tag:dFk2Uef2uVxs9KFHuJoVLw==,type:str]
    namespace: ENC[AES256_GCM,data:oBOjt6RlHfy59u0=,iv:gPs/tuQZtYVLSxbGeMSO4aVA32QDu2jZb6Zto5R9tHo=,tag:yLCMeLGj3COAaSXZvrq/Kg==,type:str]
stringData:
    CALIBRE_PASSWORD: ENC[AES256_GCM,data:jj4aKulCT0/dC4UBI34=,iv:kn1sub/JXm3aozAYEbZAcyYZQeDRG/OGJMS6qqICAtU=,tag:FXmi1IlUC1J0KsW6PUN1aQ==,type:str]
    CALIBRE_USER: ENC[AES256_GCM,data:Aa3x7VOPhvFUcg==,iv:0NxvhZ2zbGmE5uY/pHmV/ZfSMOKmScw3P0yCOdFHnCk=,tag:fzmfLB7zlGWjUfeca4eIUQ==,type:str]
    FILEBROWSER_PW: ENC[AES256_GCM,data:lQq7xlZYvUKmX1eWzKM=,iv:fhKLcfdQyz66hD3F+Be7XSN3FEC2Jfl9CcSLE8WQnks=,tag:zaHBZj4WIqKkeaCXN7As3Q==,type:str]
    FILEBROWSER_USER: ENC[AES256_GCM,data:0DRxFgMwVayNxA==,iv:RxffjsT6AnduUkCqbbtRQB3d3LIOIUNR9nT5EAi22iQ=,tag://+MqPit0F0yVWBvoOkNsQ==,type:str]
    GHCR_TOKEN: ""
    JACKETT_VPN_KEY: ENC[AES256_GCM,data:RHUJY5NcCuy3h/E6QNtfaQBX5GLeGUt+WozCexVWcPiJt7UXHWkhaGKNsnk=,iv:Tg4g3Dx6FPnpLn8dkhLJRVG+QvEft4HoPzAzxs2Ufac=,tag:XXWSWyBA8OBqBBy353hKGw==,type:str]
    LIBERA_PW: ENC[AES256_GCM,data:hG0PzSJ2mevT8lSYIoc=,iv:uSWSAH6mDYLWYEuyIki8W1lhZIffa7v6nQth2SJd4pA=,tag:nv8k4CT3KUG6xKP60bYtuA==,type:str]
    MONGO_PASS: ENC[AES256_GCM,data:mCbu0ieW8j9WxaZCwxDWQPIB+pc=,iv:3KgVP0oHhFm3xJAdlWkuZ1CDrPpEVYc7I24YaFO9m1U=,tag:RIl8tHEUPy4vaSP1TZiyFg==,type:str]
    NINJAM_PASSWORD: ENC[AES256_GCM,data:7izt2KaV,iv:DVL42547pG9U7d2uSmXKWiSGGW4escESkodboTFnDDE=,tag:kD2mZN91b5EFR/8pY8yeEQ==,type:str]
    NINJAM_USER: ENC[AES256_GCM,data:g/q8KfQ=,iv:0BRhatLrQTlyjNqitgplQ4LmhtynbRLyTOyUNalVguM=,tag:KIOQzS7g2E3EkcE/CGDNLw==,type:str]
    PLEX_CLAIM: ENC[AES256_GCM,data:GzvSZmyW8lAofa3CT0crvfK9cMyAAfZcXcI=,iv:UXG5JUcxxWV5uxJ8gqQo8ovL/LoZyBkqj69ZFszW4Uc=,tag:tF70zF2yW+ZM9ZjYTTv8xQ==,type:str]
    QBT_VPN_KEY: ENC[AES256_GCM,data:vbaG9iYaRFJ82Nd7zEhdIwSlCUUY+PsaVNeFnir0AfUhWyjKKFFn4QA2Y8Y=,iv:pa96uYT5nCMHatqJpmkQqsvls9XDYjGUJFpqPfLWv28=,tag:HYuLckDXk/4WHMBFAaotFg==,type:str]
    QUIXIT_PW: ENC[AES256_GCM,data:LWKzdQQIOUnMADEum+qivfAMwMY=,iv:SfD3PXEAhXg9I6WT4OPV/+1Kak/4xBt6LL2O+f4fPb8=,tag:CDbTWapghHiUL4sEetNpdA==,type:str]
    QUIXIT_SESSION_SECRET: ENC[AES256_GCM,data:chwDiB8UKIF095yblkng0d74Ddu98IKmqumBBJaWDGZ3uY9jV4Oow8NVtUg=,iv:Mb0cjShyORS/t823MU6XWKKjce9Dlxrrq0B+dBOMEjI=,tag:YzZs9oax5Z/+apPpiK3U/A==,type:str]
    QUIXIT_USER: ENC[AES256_GCM,data:GtZMvenZWc7SbpbzfMsF6Q==,iv:uBe7454iDjsVD8RiOLh7C7pJDT1TbLYBm1iX3OzmP+s=,tag:gf+07OeIV9NWpSr9CrLWGw==,type:str]
    SOJU_PW: ENC[AES256_GCM,data:eOd9no//ZQWkxOi3L+A=,iv:kueP+GmFcF2oGRMHrg21h9ZjmZW1AZ7pjd+NQbdv3GU=,tag:IGqCkE9sp6jGyoU10KcBgw==,type:str]
    SOULSEEK_VPN_KEY: ENC[AES256_GCM,data:0SRCpy5AZ9f84xc5vv4xu/tJm/WGFvSmL3D7STOSzVe9XKIDXT/NCexBXG4=,iv:FNcx+phP7jy1ZkXlTdy6HBHNVQB6mSDxjjpNL2BydYo=,tag:/lI4ZI3JfC4jahE1DcpOrw==,type:str]
    TS_CLIENT_ID: ENC[AES256_GCM,data:/UaThEl5tgsTJikb,iv:0GfiTGh99107HwfYng9W2WnHZq9Xzk/uIpoEuIDDy9k=,tag:613b1zW5G+qQmc6y+xAMbQ==,type:str]
    TS_CLIENT_SECRET: ENC[AES256_GCM,data:h0wODwNNCZ21kM4DB196+waYYyk0yGaVvbTcmjL22LTxnuhT5D6kyvsPFTFVEzIAySS1MW/HnBYOZg==,iv:0ilZayvmoz0pcwQUYDzE17aU1TdWquYrTJXdJkftnso=,tag:yAa2ONcdXmI9UUAWuek6ZQ==,type:str]
    TUFKIN_DB_PASSWORD: ENC[AES256_GCM,data:/PeCV9dAjfZFzXZ87vO95npBi3z+xP6ngosdCKKZKeA=,iv:E/BYQ0UrM0I9+Zy9kFb/FP45KHp42j9iiIXWg1jHjOQ=,tag:NXBWrZ/DNEP/3YgMnmevuw==,type:str]
    TUFKIN_IP_HASH_SALT: ENC[AES256_GCM,data:opEzfcyfuE1bklqrDGTmQkYmeZEHpPfwq37kv5NyOu0dnr+WUTTgxUzCq8c=,iv:lShzkdPUoOJDgRGhUZ7qVB+fHN//VA4U+sf6KsCOENw=,tag:zfQI1EfJ1STOULqBGsKgPw==,type:str]
    TUFKIN_JWT_SESSION_SECRET: ENC[AES256_GCM,data:/SanK3UQMCoofuNFi2uCKFWwmi0umQX7DgdeTI/VIXHNl87BtY/krWtdSvU=,iv:I5/G1TvFNJBnHaNyTqnMd8uAxoUvFOYpBgCc8y5i+gY=,tag:jHbGrkWb7tqsqiGuztQUWA==,type:str]
type: ENC[AES256_GCM,data:HVdTWkgq,iv:pW38zlsm5rWm4aqwoEXawKfoy126ScTkNZnbmE8ep6Q=,tag:8aUKVqZqm3aAsQ8xupimTQ==,type:str]
sops:
    age:
        - recipient: age15tc0zhh8daq8xk4ydnzhzjfp8nh3sve93a65r5wfypk38lzgdqkqp5l4wv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJZXY0SXBXd00wVHh2Rm56
            czY4ell1dms4alhKSFNubTRmb0VhSG4rMEZZCm03YUFvUllUSTR2cHBrR2J6ZzJE
            UmYrSmZ1REZOblpZMUNVb2pxTnJkcHcKLS0tIE8vOTRWeFhvdS8rMERxZU9jNlBp
            YWFMdVQyZXhMWklhRkdhcVlxWTNKYmsKQLIruf0wRoJKQLPWe8AhXgRVzw1x25Q5
            tdKWJtPLAFmk2/0EZRFkgevsmrFH00eINMs7MrzP7myFhuSkmNzNrQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T07:17:59Z"
    mac: ENC[AES256_GCM,data:bK4zI3t/AJtHSrZEQb2aWjVdVepqPeUvCTUcFYk25kYNrpWXle4MESSwGAXwql9WPLZDxqTGoVJia3L0RLNsrc9MC0G9h6MFsGCLQ1FojusF8L/6sIhwxl7N/hnUXiyE8OTR3D2/HTr21Dhr4X3p/yQjsJmU6UndIBsOzK0J924=,iv:ivRcxPWqPvxebIB4MLhsXJWezGJPIyySu4jLHs55OZU=,tag:PduekYWkFG2FsnR1UwzLKQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
