apiVersion: ENC[AES256_GCM,data:ymE=,iv:mDwYY6P8OG9oq7kHAHEvFRxT/XOHcqOUSFRfRyZhalc=,tag:wcIqmBGoMSTLK5gsFD0TpA==,type:str]
kind: ENC[AES256_GCM,data:hg3ZFw6r,iv:aJ4lp19iDRrpN3d5zXKyF0kNJyyCIOdFBlDL1Ozexq4=,tag:TvzE/txkZrOJKLs5Kof+WA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:CtzTopWMVQgvltzJoioR,iv:Yzhf8G6gj4I9HH8oeMSFZmkRVuqNlbbD1FicEUeDD2g=,tag:YnsDaOaosmM3bfmUXyO1mg==,type:str]
    namespace: ENC[AES256_GCM,data:AAiF3PJChXUD9lY=,iv:PoXiFte9KiHQN+pnB65ZDKsPu4MkxVOIwwJjDWPhve4=,tag:7EDJTy+hEbb8v50GRgX7Ug==,type:str]
type: ENC[AES256_GCM,data:G7TUd38D,iv:rTL3V1UqA0u+ZeDiS502rhkutKBeygv3XtnQ+zC1FFw=,tag:+2LeBzdwEnTnKk7Jktd0Ag==,type:str]
stringData:
    #ENC[AES256_GCM,data:E9ENEexE98oCxoLgz4LAjDZMVIITWj46,iv:FcItgfysrT7NsrpVyDUhvS95VeFlwsKv70So97Kxqwc=,tag:uW42lUgaen3B/eVz4b0q9A==,type:comment]
    NINJAM_USER: ENC[AES256_GCM,data:2VnZsOM=,iv:FlQKudXAkZ5a8Dv/sEBb5kb0kBgHrQ3riKse05eDF2Y=,tag:WPIGWXTBknjUaa1jTWvpRA==,type:str]
    NINJAM_PASSWORD: ENC[AES256_GCM,data:q5UPFUEt,iv:U07Bz5hLxT8c0yJklXdHhDH9LhPicxUssNXOACNCl7s=,tag:9ShMkKKGRUBnNsiLHMWfbg==,type:str]
    FILEBROWSER_USER: ENC[AES256_GCM,data:NNA9+bcFDR0D8g==,iv:so221uL8GcC0Zg67i/Zgpyb0Dq8/+ROf4Fd1LtEpMkA=,tag:cezcaPbpuYeBCe30X6x6jQ==,type:str]
    FILEBROWSER_PW: ENC[AES256_GCM,data:wx7AdybqKLEoXUNQsmk=,iv:DWstIJyO+PYK0DL+OLFRNVsJoW2JRiaVbZwxG0I2n5E=,tag:nB1/GOopg7EWgLaeMQMAAA==,type:str]
    QUIXIT_USER: ENC[AES256_GCM,data:jH9VrtrnWAmptwWMyYXNAw==,iv:E1TDSJ7I2553HAcTuF8FIxqxyKywY3MVRJzeRFAK8Qo=,tag:ry/OQi6Kb2h/fLdbwhNcNQ==,type:str]
    QUIXIT_PW: ENC[AES256_GCM,data:yBAZZjmvjv88V4MxJSgK0GlsRWg=,iv:aWXMzX4EY09d86Ti1491Fttpz8rRD/gaefUjAVVTBds=,tag:1gYPKCTbPcl+/aBW7ZBydg==,type:str]
    SOJU_PW: ENC[AES256_GCM,data:coa1567QLO2u2nsKP9M=,iv:qEaDu7UcLrxF0m1ctPUI/pXMskeYqFV9SWom7wBbIs8=,tag:wZZSZg8Rhsa6yeMsF8O1Lw==,type:str]
    LIBERA_PW: ENC[AES256_GCM,data:STzjWLT3W+ZMQJuY5KI=,iv:TKyqvbOc3CY78NDrKpKuoqACfSvNBZAJkxOBRrP3nxI=,tag:I7Ar0qfjrNghmeDrAqLUXw==,type:str]
    CALIBRE_USER: ENC[AES256_GCM,data:IAUVVddP5Ec73w==,iv:uAc9TGlKPZ78T5PJsoP/CSUsFrgPiuODneY+7lqr9Jc=,tag:Rd8wGc7NwG27oG7Xj6seMw==,type:str]
    CALIBRE_PASSWORD: ENC[AES256_GCM,data:hVRzMDva3efgSaqJpC8=,iv:NyOaYn6NWCRhvXfjOxjmz5eO332Ho/fE9vwYycN8BDI=,tag:HvG8nsRnEMWI4nASMBEXhQ==,type:str]
    PLEX_CLAIM: ENC[AES256_GCM,data:K58jO687lxAq3IeAwKLWEhreTnTFSbiE17g=,iv:jTe1BVvrUrgzWsNd6ohm/Y9u02X/iaxW0FZnredAYfU=,tag:pThaff7YL3Gq9O7NU1VLmA==,type:str]
    MONGO_PASS: ENC[AES256_GCM,data:rjVu6ZGbH+DM/w9AsiME0FNodds=,iv:Amj4idP+DMo7CxvoF2TudkYW8EMexLs7bmPNvsl5BbQ=,tag:9QCn2W2iocKLQG203uZHFA==,type:str]
    #ENC[AES256_GCM,data:1JovQ1SKMDVrWANxq4vmX3bWcVl9LGmjVIjlNOx1UN2rqw==,iv:V0bTvxo5634VhkMzacAXhLzea5tkN+iAg4DhSkw+wqM=,tag:vTVPvu//lX1QufL3vbQzYw==,type:comment]
    SOULSEEK_VPN_KEY: ENC[AES256_GCM,data:SlQTnIRvhokGAidUIABjAANHjx1jzGNS4cArHz7ScE7mw2dUmPfE4ELTtwI=,iv:LKyDm/aRss9fVnnrqofaOkLno9+93Ci64iCz2TXHgLE=,tag:sJqFKsMFf/X+E/q2tWk4iA==,type:str]
    QBT_VPN_KEY: ENC[AES256_GCM,data:GpyRyZcYWpYJbionP/i2LZAOwC5PykAtqa/nOdBO3r6r/2zTgon0BTn8QoM=,iv:8TTDLZHjP0UkzNmt8Zyt4ryvgVyAAaQSYAhGT/ZDKnk=,tag:o7WD15qFV1wXC/MhmzVkQA==,type:str]
    JACKETT_VPN_KEY: ENC[AES256_GCM,data:kH7nV1zqJk9ehjn2290Wc4ePeorCjH+6elM8me6IV1HE99Yuljbpkzrri+M=,iv:ijrWjSL2fX7Egnq3ErdpznxONUjMxKJEdA2I8qylCkg=,tag:sG8cE7RpELGwPCASC5e6bg==,type:str]
    #ENC[AES256_GCM,data:maAr4aRTCA==,iv:D6OPITi1Wm+DdTn1FayO33KVJO4vPPVh74jsYxTjOGg=,tag:91QE/QGb+vpiqB/Zdk4byw==,type:comment]
    TUFKIN_DB_PASSWORD: ENC[AES256_GCM,data:j6mFOijeqRPUeRHQe4A1s5S+D75mrJhbQNUT4Ah447g=,iv:4YG4NgNUwGB21tnXhl7z9jy8suKetHCa6IPkQd99FQE=,tag:sKsJBfa+P4xTAecFB0SMRw==,type:str]
    TUFKIN_JWT_SESSION_SECRET: ENC[AES256_GCM,data:QNMNp0oc4B8F+it2PTXPhJMop1OE6RCALoaZOshjUmi0hzm7kVC9Gnyu4B8=,iv:hiEMPHt5P0QUhiCa0rLwTbZVnLXosntcdEb3L8vuHDk=,tag:rbwfQp8nZo8FQy9mJcvYVQ==,type:str]
    TUFKIN_IP_HASH_SALT: ENC[AES256_GCM,data:WxLggxNBv6+7/JFp2gxug3Ks9+gqeTOmVWW9vjnlMpdDhejQbuCgok0KQBQ=,iv:hp5lFfNMRmD99W1YXkMSt/jJd3tFsRjbrQWvmuHvQZI=,tag:vMN2HkVno+lD69TskNZVFg==,type:str]
    #ENC[AES256_GCM,data:v+0B2hY+tRAxqXLuf0pySQ==,iv:vQKAMAKdQTfIjAQ/tBrqXkVI9NjAGuLukaoogB2whc4=,tag:rm5NpS7Rzm5Zd05f0PgU1Q==,type:comment]
    TS_CLIENT_ID: ENC[AES256_GCM,data:LhVy5M1kl8iaVBUv,iv:Ci9Gp55X+dP1ouA85KN9Tta5IRpkEGiR/lPCgrBjDEU=,tag:1D27trE1r9eQjJb6CwW15Q==,type:str]
    TS_CLIENT_SECRET: ENC[AES256_GCM,data:vpC2W6jpj5cj6NJC/JuRUVEQZuF3FEyTP4LdauUtUrMX+pae2Jfk0PeB+FpTt9xvcuWWK9So1KkjNQ==,iv:3aUMt735H2z3I4cKoJuhaYByfRHXaMVXW3IuSbVu014=,tag:qcewSGJBEAdXI/ocsL5zhg==,type:str]
sops:
    age:
        - recipient: age15tc0zhh8daq8xk4ydnzhzjfp8nh3sve93a65r5wfypk38lzgdqkqp5l4wv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlbXhUL3ZKeTUzUGtmcTZ2
            Unp5UDRlWENjTTRJVkVETCtRMVhqc2VlS3h3ClhyQjRmajBMTVBJMCthdVJlZ0NV
            NThYaHFkVU9pZm4wOU9sSG5xendFeUUKLS0tIE5MSmkwS0NMSVBvSUNUSnJaUFVp
            RkQrRTUxL2lwaitTZ1YyMjMvanZ4YkEKMgTkZPQeS16bfQrkTtPIPKqj0+DwNHLX
            ZomDwYCwYqqB9Hf0tjOX16UTP0zmZLpDJKor2e3PErw1GBAlAwgTvA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T02:17:50Z"
    mac: ENC[AES256_GCM,data:R3exKEF940GU3XY013z++bnO/qW4IcV3sayaVvKpD/XkpizywRB2spCh97HreKXW26X13Lo7gNB6JFTzxNIbAvVQxV/uZesblzw/Ui4cokmExzvG6PIyBQHesHXofpfrbbCPdP/29fpbCgWrZg5HP4tknuD4M7HEJSIoVXLr0yI=,iv:axTxWVnqb6M2W9G+MSDneWWAnZq36XeR5T4K3AWM2LU=,tag:+vMcf3Ybp6GheMmplf3NQg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
