controller:
 allowSnippetAnnotations: true
 service:
  ports:
   irc:
    port: 6667
    targetPort: 6667
    protocol: TCP
   irc-tls:
    port: 6697
    targetPort: 6697
    protocol: TCP
tcp:
 6667: 'irc/soju:6667'
 6697: 'irc/soju:6697'

tcpConfigMapNamespace: 'ingress-nginx'
tcpConfigMapName: 'tcp-services'
