apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
  namespace: tufkin
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: '{"auths":{"ghcr.io":{"username":"ianhundere","password":"${GHCR_TOKEN}"}}}'
