apiVersion: v1
kind: Secret
metadata:
  name: tufkin-credentials
  namespace: tufkin
type: Opaque
stringData:
  db-password: ${TUFKIN_DB_PASSWORD}
  jwt-session-secret: ${TUFKIN_JWT_SESSION_SECRET}
  ip-hash-salt: ${TUFKIN_IP_HASH_SALT}
  smtp-password: ${TUFKIN_SMTP_PASSWORD}
  admin-token: ${TUFKIN_ADMIN_TOKEN}
