apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ninjam-server-ssd
  namespace: ninjam
  labels:
    app: ninjam-server
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
