apiVersion: v1
kind: PersistentVolume
metadata:
  name: ninjam-server-ssd
  namespace: ninjam
  labels:
    app: ninjam-server
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/ssd/ninjam