apiVersion: v1
kind: Service
metadata:
  annotations:
    tailscale.com/hostname: "ninjam"
  namespace: ninjam
  labels:
    app: ninjam-server
  name: ninjam-server
spec:
  ports:
    - port: 2050
      targetPort: 2050
      protocol: TCP
  selector:
    app: ninjam-server
  type: LoadBalancer
  loadBalancerClass: tailscale
  externalIPs:
    - "${METAL_LB_IP1}"
