apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ninjam-server
  namespace: ninjam
  labels:
    app: ninjam-server
    storage.k8s.io/name: nfs
spec:
  storageClassName: nfs-rpik3s
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
