apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: transmission
  name: transmission
  namespace: media
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: transmission
  template:
    metadata:
      labels:
        app: transmission
    spec:
      hostname: transmission
      initContainers:
        - name: sysctl-setup
          image: busybox
          command:
            [
              "sh",
              "-c",
              "sysctl -w net.ipv4.conf.all.rp_filter=2 && sysctl -w net.ipv6.conf.all.disable_ipv6=1",
            ]
          securityContext:
            privileged: true
        - name: protonwire
          image: ghcr.io/tprasadtp/protonwire:7.2.5
          restartPolicy: Always
          env:
            - name: WIREGUARD_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: openvpn
                  key: key
            - name: PROTONVPN_SERVER
              value: "IS-NL#1"
            - name: DEBUG
              value: "0"
            - name: KILL_SWITCH
              value: "1"
            - name: IPCHECK_URL
              value: "https://protonwire-api.vercel.app/api/client/exp/clientip"
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
      containers:
        - env:
            - name: TRANSMISSION_DOWNLOAD_DIR
              value: /downloads/transmission
            - name: GLOBAL_APPLY_PERMISSIONS
              value: "false"
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          image: linuxserver/transmission:4.0.4
          imagePullPolicy: IfNotPresent
          name: transmission
          ports:
            - containerPort: 9091
              name: http
              protocol: TCP
          resources:
            requests:
              cpu: 500m
              memory: 320Mi
          volumeMounts:
            - mountPath: /config/transmission-home
              name: media-config
              subPath: transmission-data/transmission-home
            - mountPath: /data/watch
              name: media-config
              subPath: transmission-data/watch
            - mountPath: /data/incomplete
              name: media-data
              subPath: incomplete/transmission
            - mountPath: /downloads/transmission
              name: media-data
              subPath: downloads/transmission
      dnsPolicy: None
      dnsConfig:
        nameservers: ["1.1.1.1", "1.0.0.1"]
      restartPolicy: Always
      volumes:
        - name: media-config
          persistentVolumeClaim:
            claimName: media-config
        - name: media-data
          persistentVolumeClaim:
            claimName: media-data
