apiVersion: v1
kind: Service
metadata:
  labels:
    app: transmission-openvpn
  name: transmission-openvpn
  namespace: media
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 9091
  selector:
    app: transmission-openvpn
  type: ClusterIP
