apiVersion: v1
kind: Service
metadata:
  labels:
    app: transmission
  name: transmission
  namespace: media
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 9091
  selector:
    app: transmission
  type: ClusterIP
