apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: transmission-openvpn
  name: transmission-openvpn
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transmission-openvpn
      release: transmission
  template:
    metadata:
      labels:
        app: transmission-openvpn
        release: transmission
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - jackett
            topologyKey: kubernetes.io/hostname
      containers:
        - env:
            - name: OPENVPN_PROVIDER
              value: PROTONVPN
            - name: OPENVPN_USERNAME
              valueFrom:
                secretKeyRef:
                  key: username
                  name: openvpn
            - name: OPENVPN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: openvpn
            - name: OPENVPN_CONFIG
              value: node-ch-05.protonvpn.net.tcp,node-ch-08.protonvpn.net.tcp,node-nl-20.protonvpn.net.tcp,node-nl-43.protonvpn.net.tcp
            - name: OPENVPN_OPTS
              value: "--mute-replay-warnings"
            - name: LOCAL_NETWORK
              value: "${CIDR}"
            - name: TRANSMISSION_PEER_PORT
              value: "47444"
            - name: TRANSMISSION_DOWNLOAD_DIR
              value: /downloads/transmission
            - name: GLOBAL_APPLY_PERMISSIONS
              value: "false"
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          image: haugene/transmission-openvpn:4.0
          imagePullPolicy: IfNotPresent
          name: transmission-openvpn
          livenessProbe:
            failureThreshold: 12
            initialDelaySeconds: 60
            periodSeconds: 30
            successThreshold: 1
            httpGet:
              path: /web/
              port: http
            timeoutSeconds: 10
          readinessProbe:
            failureThreshold: 12
            initialDelaySeconds: 60
            timeoutSeconds: 10
            periodSeconds: 30
            successThreshold: 1
            httpGet:
              path: /web/
              port: http
          ports:
            - containerPort: 9091
              name: http
              protocol: TCP
          resources:
            requests:
              cpu: 1
              memory: 512Mi
            limits:
              cpu: 1500m
              memory: 1.5Gi
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          volumeMounts:
            - mountPath: /data/transmission-home
              name: media-ssd
              subPath: configs/transmission-data/transmission-home
            - mountPath: /data/watch
              name: media-ssd
              subPath: configs/transmission-data/watch
            - mountPath: /data/incomplete
              name: media-hdd
              subPath: incomplete
            - mountPath: /downloads/transmission
              name: media-hdd
              subPath: downloads/transmission
            - mountPath: /dev/net/tun
              name: dev-tun
      dnsConfig:
        nameservers:
          - 8.8.8.8
          - 8.8.4.4
      dnsPolicy: None
      restartPolicy: Always
      volumes:
        - name: media-ssd
          persistentVolumeClaim:
            claimName: media-ssd
        - name: media-hdd
          persistentVolumeClaim:
            claimName: hdd
        - hostPath:
            path: /dev/net/tun
            type: ""
          name: dev-tun
