apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: transmission
  name: transmission
  namespace: media
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: transmission
  template:
    metadata:
      labels:
        app: transmission
    spec:
      hostname: transmission
      initContainers:
        - name: sysctl-setup
          image: busybox
          command:
            [
              "sh",
              "-c",
              "sysctl -w net.ipv4.conf.all.rp_filter=2 && sysctl -w net.ipv6.conf.all.disable_ipv6=1",
            ]
          securityContext:
            privileged: true
        - name: protonwire
          image: ghcr.io/tprasadtp/protonwire:7.3.0-alpha2
          restartPolicy: Always
          env:
            - name: WIREGUARD_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: transmission
                  key: key
            - name: PROTONVPN_SERVER
              value: "IS-NO#1"
            - name: DEBUG
              value: "0"
            - name: KILL_SWITCH
              value: "1"
            - name: IPCHECK_URL
              value: "https://checkip.amazonaws.com/"
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          command: ["/bin/bash", "-c"]
          args:
            [
              "/usr/bin/protonwire connect --container & sleep 10; natpmpc -a 1 0 udp 60 -g 10.2.0.1; natpmpc -a 1 0 tcp 60 -g 10.2.0.1 | grep -oP 'public\\ port\\ \\K\\w+' > /config/protonvpn-port; echo \"Port written to protonvpn-port file\"; cat /config/protonvpn-port; while true; do date; natpmpc -a 1 0 udp 60 -g 10.2.0.1 && natpmpc -a 1 0 tcp 60 -g 10.2.0.1 || { echo -e \"ERROR with natpmpc command \\a\"; break; }; sleep 45; done",
            ]
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
      containers:
        - env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          image: linuxserver/transmission:4.0.4
          imagePullPolicy: IfNotPresent
          name: transmission
          ports:
            - name: http
              containerPort: 9091
              protocol: TCP
          resources:
            requests:
              cpu: 500m
              memory: 320Mi
          volumeMounts:
            - mountPath: /config
              name: media-config
              subPath: transmission
            - mountPath: /downloads/incomplete
              name: media-data
              subPath: incomplete/transmission
            - mountPath: /downloads/complete
              name: media-data
              subPath: downloads/transmission
      dnsPolicy: None
      dnsConfig:
        nameservers: ["1.1.1.1", "1.0.0.1"]
      restartPolicy: Always
      volumes:
        - name: media-config
          persistentVolumeClaim:
            claimName: media-config
        - name: media-data
          persistentVolumeClaim:
            claimName: media-data
