apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: transmission
  namespace: media
data:
  username: ${TRANSMISSION_VPN_KEY}
  password: ${TRANSMISSION_VPN_KEY}
  key: ${TRANSMISSION_VPN_KEY}
