apiVersion: apps/v1
kind: Deployment
metadata:
 labels:
  app: transmission
 name: transmission
 namespace: media
spec:
 replicas: 1
 strategy:
  type: Recreate
 revisionHistoryLimit: 3
 selector:
  matchLabels:
   app: transmission
 template:
  metadata:
   labels:
    app: transmission
  spec:
   hostname: transmission
   initContainers:
    - name: sysctl-setup
      image: busybox
      command:
       [
        'sh',
        '-c',
        'sysctl -w net.ipv4.conf.all.rp_filter=2 && sysctl -w net.ipv6.conf.all.disable_ipv6=1 && sysctl -w net.ipv4.ip_forward=1',
       ]
      securityContext:
       privileged: true
   containers:
    - name: gluetun
      image: qmcgaw/gluetun:v3.40.0
      securityContext:
       capabilities:
        add:
         - NET_ADMIN
       privileged: true
      env:
       - name: VPN_SERVICE_PROVIDER
         value: protonvpn
       - name: VPN_TYPE
         value: wireguard
       - name: WIREGUARD_PRIVATE_KEY
         valueFrom:
          secretKeyRef:
           name: transmission
           key: key
       - name: WIREGUARD_ENDPOINT_IP
         value: '138.199.6.178'
       - name: SERVER_COUNTRIES
         value: 'Switzerland'
       - name: VPN_PORT_FORWARDING
         value: 'on'
       - name: FIREWALL
         value: 'yes'
       - name: HEALTHCHECK_TARGET
         value: 'ip.me:443'
      ports:
       - containerPort: 9091
         protocol: TCP
      volumeMounts:
       - mountPath: /dev/net/tun
         name: tun-device
      resources:
       requests:
        cpu: 100m
        memory: 256Mi
       limits:
        memory: 256Mi
    - env:
       - name: PUID
         value: '1000'
       - name: PGID
         value: '1000'
       - name: TRANSMISSION_RPC_HOST_WHITELIST
         value: '*'
       - name: TRANSMISSION_BIND_ADDRESS_IPV4
         value: '0.0.0.0'
       - name: TRANSMISSION_PEER_SOCKET_TOS
         value: 'lowcost'
      image: linuxserver/transmission:4.0.6
      imagePullPolicy: IfNotPresent
      name: transmission
      resources:
       requests:
        cpu: 800m
        memory: 1Gi
       limits:
        memory: 1Gi
      volumeMounts:
       - mountPath: /config
         name: media-config
         subPath: transmission
       - mountPath: /downloads/incomplete
         name: media-data
         subPath: incomplete/transmission
       - mountPath: /downloads/complete
         name: media-data
         subPath: downloads/transmission
   restartPolicy: Always
   volumes:
    - name: media-config
      persistentVolumeClaim:
       claimName: media-config
    - name: media-data
      persistentVolumeClaim:
       claimName: media-data
    - name: tun-device
      hostPath:
       path: /dev/net/tun
