apiVersion: batch/v1
kind: CronJob
metadata:
  name: manage-sample-packs
  namespace: quixit
spec:
  # Run at 23:59 every Thursday (just before Friday)
  schedule: "59 23 * * 4"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: pack-manager
            image: curlimages/curl:latest
            command:
            - /bin/sh
            - -c
            - |
              # First, close the current pack if it exists
              CURRENT_PACK=$(curl -s http://quixit-backend-service.quixit/api/samples/packs | jq -r '.currentPack')
              if [ "$CURRENT_PACK" != "null" ]; then
                PACK_ID=$(echo $CURRENT_PACK | jq -r '.ID')
                echo "Closing pack $PACK_ID"
                curl -X POST http://quixit-backend-service.quixit/api/admin/packs/$PACK_ID/close
              fi

              # Wait a moment to ensure the close is processed
              sleep 5

              # Create new pack for the upcoming week
              NEXT_FRIDAY=$(date -d "tomorrow" +%Y-%m-%d)
              echo "Creating new pack for $NEXT_FRIDAY"
              curl -X POST http://quixit-backend-service.quixit/api/admin/packs \
                -H "Content-Type: application/json" \
                -d "{\"title\":\"Sample Pack $NEXT_FRIDAY\",\"description\":\"Weekly sample pack starting $NEXT_FRIDAY\"}"
          restartPolicy: OnFailure 