apiVersion: v1
kind: ConfigMap
metadata:
 name: lounge
 namespace: irc
data:
 config.js: |
  module.exports = {
    public: false,
    host: "0.0.0.0",
    port: 80,
    reverseProxy: true,
    prefetchStorage: true,
    fileUpload: {
      enable: true,
      maxFileSize: 10485760
    },
    defaults: {
      name: "soju",
      host: "soju",
      port: 6667,
      tls: false,
      rejectUnauthorized: false,
      nick: "F-i-G",
      username: "admin/irc.libera.chat@thelounge",
      password: "${LOUNGE_PW}",
      join: "#quixit"
    }
  };
