apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 namespace: irc
 name: irc-ingress
 annotations:
  nginx.ingress.kubernetes.io/ssl-redirect: 'false'
spec:
 ingressClassName: nginx
 rules:
  - host: irc.${QUIXIT_HOST}
    http:
     paths:
      - backend:
         service:
          name: lounge
          port:
           number: 80
        path: /
        pathType: Prefix
