apiVersion: v1
kind: Service
metadata:
 name: lounge
 namespace: irc
 annotations:
  tailscale.com/hostname: 'lounge'
  tailscale.com/expose: 'true'
spec:
 selector:
  app: lounge
 ports:
  - name: http
    port: 80
    targetPort: 80
 type: ClusterIP
