apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: soulseek
  namespace: media
stringData:
  vpn-key: ${SOULSEEK_VPN_KEY}
  api-key: ${SLSKD_API_KEY}
  slsk-username: ${SOULSEEK_USERNAME}
  slsk-password: ${SOULSEEK_PASSWORD}
