---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # helm repositories
  - sources/jetstack.yml
  - sources/nfs-subdir.yml
  - sources/tailscale.yml
  - sources/envoy-gateway-oci.yml
  # cert-manager
  - cert-manager/namespace.yml
  - cert-manager/release.yml
  - cert-manager/clusterissuer.yml
  - cert-manager/internal-ca.yml
  # metallb
  - metallb/namespace.yml
  - metallb/config.yml
  # envoy-gateway
  - envoy-gateway/namespace.yml
  - envoy-gateway/release.yml
  - envoy-gateway/gatewayclass.yml
  - envoy-gateway/envoyproxy.yml
  - envoy-gateway/gateway.yml
  # nfs-provisioner
  - nfs-provisioner/namespace.yml
  - nfs-provisioner/video-storage.yml
  - nfs-provisioner/music-storage.yml
  - nfs-provisioner/config-storage.yml
  # image-automation
  - image-automation/imagerepositories.yml
  - image-automation/imagepolicies.yml
  - image-automation/imageupdateautomation.yml
  # system-upgrade-controller - uncomment when ready to upgrade k3s
  # - system-upgrade-controller/
