---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: soju-cert
  namespace: irc
spec:
  secretName: soju-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - ${SOJU_HOST}
