apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: unifi
  name: unifi
  labels:
    app: unifi
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
status: {}
