apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: unifi
  name: unifi-controller
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    cert-manager.io/issue-temporary-certificate: "true"
    acme.cert-manager.io/http01-edit-in-place: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/limit-connections: "10"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-hide-header: "server"
    nginx.ingress.kubernetes.io/hsts: "true"
    nginx.ingress.kubernetes.io/hsts-max-age: "31536000"
    nginx.ingress.kubernetes.io/hsts-include-subdomains: "true"
    nginx.ingress.kubernetes.io/hsts-preload: "true"
    nginx.ingress.kubernetes.io/x-frame-options: "DENY"
    nginx.ingress.kubernetes.io/x-content-type-options: "nosniff"
    nginx.ingress.kubernetes.io/referrer-policy: "strict-origin-when-cross-origin"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - "${UNIFI_HOST}"
      secretName: unifi-cert
  rules:
    - host: "${UNIFI_HOST}"
      http:
        paths:
          - backend:
              service:
                name: unifi-controller
                port:
                  number: 8443
            path: /
            pathType: Prefix
