apiVersion: v1
kind: ConfigMap
metadata:
  namespace: unifi
  name: unifi-controller-mongo-init-script
data:
  init-mongo.js: |
    db.getSiblingDB("unifi").createUser({
      user: "unifi",
      pwd: "${MONGO_PASS}",
      roles: [
        { role: "dbOwner", db: "unifi" },
        { role: "dbOwner", db: "unifi_stat" }
      ]
    });
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: unifi
  labels:
    app: unifi-controller
  name: unifi-controller
spec:
  replicas: 1
  strategy:
    type: Recreate
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: unifi-controller
  template:
    metadata:
      labels:
        app: unifi-controller
    spec:
      volumes:
        - name: unifi
          persistentVolumeClaim:
            claimName: unifi
        - name: mongo-init-script
          configMap:
            name: unifi-controller-mongo-init-script
      initContainers:
        - name: unifi-db
          image: docker.io/mongo:3.6.23
          restartPolicy: Always
          volumeMounts:
            - name: unifi
              mountPath: /data/db
              subPath: data/db
            - name: mongo-init-script
              mountPath: /docker-entrypoint-initdb.d
              readOnly: true
          ports:
            - containerPort: 27017
          resources:
            requests:
              cpu: 300m
              memory: 1.250Gi
            limits:
              memory: 1.250Gi
      containers:
        - name: unifi-network-application
          image: lscr.io/linuxserver/unifi-network-application:8.6.9
          env:
            - name: PGID
              value: "1000"
            - name: PUID
              value: "999"
            - name: TZ
              value: "Etc/UTC"
            - name: MONGO_USER
              value: "unifi"
            - name: MONGO_PASS
              value: "${MONGO_PASS}"
            - name: MONGO_HOST
              value: "localhost"
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_DBNAME
              value: "unifi"
          ports:
            - containerPort: 3478
              protocol: UDP
            - containerPort: 10001
              protocol: UDP
            - containerPort: 8080
            - containerPort: 8443
            - containerPort: 8843
            - containerPort: 8880
            - containerPort: 6789
          volumeMounts:
            - name: unifi
              mountPath: /config
          resources:
            requests:
              cpu: 2
              memory: 1800Mi
            limits:
              memory: 1800Mi
