apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: unifi
  name: unifi-controller
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
spec:
  tls:
  - hosts:
    - host.name
    secretName: unifi-cert
  rules:
  - host: host.name
    http:
      paths:
        - path: /
          backend:
            serviceName: unifi-controller
            servicePort: 8443
