apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: unifi
  name: unifi
  labels:
    app: unifi-controller
    storage.k8s.io/name: nfs
spec:
  storageClassName: nfs-rpik3s
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
