apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: unifi
  name: unifi-ssd
  labels:
    app: unifi-controller
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
