apiVersion: apps/v1
kind: Deployment
metadata:
  name: calibre
  namespace: media
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: calibre
  template:
    metadata:
      labels:
        app: calibre
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: calibre
          image: lscr.io/linuxserver/calibre-web:0.6.24
          ports:
            - containerPort: 8083
              name: http
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "UTC"
            - name: DOCKER_MODS
              value: linuxserver/mods:universal-calibre
            - name: CALIBRE_PORT
              value: "8083"
          volumeMounts:
            - name: media-config
              mountPath: /config
              subPath: calibre/config
            - name: media-config
              mountPath: /books
              subPath: calibre/library
          resources:
            requests:
              memory: "1Gi"
              cpu: "200m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 300
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 240
            periodSeconds: 20
            timeoutSeconds: 10
            failureThreshold: 5
      volumes:
        - name: media-config
          persistentVolumeClaim:
            claimName: media-config
