apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: radarr
  name: radarr
  namespace: media
spec:
  replicas: 1
  strategy:
    type: Recreate
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
      enableServiceLinks: false
      containers:
      - env:
        - name: PUID
          value: '1000'
        - name: PGID
          value: '1000'
        - name: RADARR__POSTGRES__HOST
          value: media-postgres
        - name: RADARR__POSTGRES__PORT
          value: '5432'
        - name: RADARR__POSTGRES__USER
          value: media
        - name: RADARR__POSTGRES__PASSWORD
          valueFrom:
            secretKeyRef:
              name: media-postgres
              key: password
        - name: RADARR__POSTGRES__MAINDB
          value: radarr-main
        - name: RADARR__POSTGRES__LOGDB
          value: radarr-log
        image: linuxserver/radarr:6.1.1 # {"$imagepolicy": "flux-system:radarr"}
        imagePullPolicy: IfNotPresent
        name: radarr
        ports:
        - containerPort: 7878
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 1
            memory: 1Gi
          limits:
            memory: 1Gi
        volumeMounts:
        - mountPath: /config
          name: media-config
          subPath: radarr
        - mountPath: /downloads/complete
          name: media-data
          subPath: downloads/qbittorrent
        - mountPath: /movies
          name: media-data
          subPath: library/movies
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
      - name: media-config
        persistentVolumeClaim:
          claimName: media-config
      - name: media-data
        persistentVolumeClaim:
          claimName: media-data
      nodeSelector:
        kubernetes.io/arch: arm64
