apiVersion: batch/v1
kind: CronJob
metadata:
  name: create-sample-pack
spec:
  # Run at 00:00 every Friday
  schedule: "0 0 * * 5"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: pack-creator
            image: curlimages/curl:latest
            command:
            - /bin/sh
            - -c
            - |
              TITLE="Sample Pack $(date +%Y-%m-%d)"
              curl -X POST http://quixit-backend-service/api/admin/packs \
                -H "Content-Type: application/json" \
                -d "{\"title\":\"$TITLE\",\"description\":\"Weekly sample pack starting $(date +%Y-%m-%d)\"}"
          restartPolicy: OnFailure
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: close-sample-pack
spec:
  # Run at 00:00 every Friday (before creating new pack)
  schedule: "0 0 * * 5"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: pack-closer
            image: curlimages/curl:latest
            command:
            - /bin/sh
            - -c
            - |
              # Get current pack ID
              PACK_ID=$(curl -s http://quixit-backend-service/api/samples/packs | jq -r '.currentPack.ID')
              if [ ! -z "$PACK_ID" ]; then
                curl -X POST http://quixit-backend-service/api/admin/packs/$PACK_ID/close
              fi
          restartPolicy: OnFailure 